local kScript = "CabinInterior"
local kScene = "adv_cabinInterior202"
local PreloadAssets = function()
  if Platform_NeedShaderPreload() then
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "134")
    RenderPreloadShader("SceneShadowMap_QLo.t3fxb", "0")
    RenderPreloadShader("SceneShadowMapAlpha_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_LGT_QLo.t3fxb", "199")
    RenderPreloadShader("FX_Null_QLo.t3fxb", "0")
    RenderPreloadShader("DirectionalLightShadow_QLo.t3fxb", "1024")
    RenderPreloadShader("SceneToonOutline2_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_DTL_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_1SKN_LGT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "260")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_QLo.t3fxb", "131")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "3")
    RenderPreloadShader("ScenePreZ_QLo.t3fxb", "128")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "260")
    RenderPreloadShader("Mesh_QLo.t3fxb", "387")
    RenderPreloadShader("Mesh_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_DTL_SDTL_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_QLo.t3fxb", "266")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "142")
    RenderPreloadShader("Mesh_QLo.t3fxb", "138")
    RenderPreloadShader("Mesh_QLo.t3fxb", "394")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "142")
    RenderPreloadShader("SceneShadowMap_1SKN_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_QLo.t3fxb", "263")
    RenderPreloadShader("SceneToonOutline2_QLo.t3fxb", "128")
  end
end
function CabinInterior()
  Game_NewScene(kScene, kScript)
  PreloadAssets()
  if Game_GetDebug() then
    if LogicGet("1CabinInterior - Intruder Arrives") then
      Game_SetSceneDialogNode("cs_leaveSarahRoom")
      Yield()
    end
    if LogicGet("1CabinInterior - Group Returns") then
      Game_SetSceneDialogNode("cs_groupReturns")
      Yield()
    end
  end
  Game_StartScene(true)
end
SceneOpen(kScene, kScript)
SceneAdd("ui_openingCredits")
