local kScript = "LodgeExteriorFront"
local kScene = "adv_lodgeExteriorFront"
local PreloadAssets = function()
  if Platform_NeedShaderPreload() then
    RenderPreloadShader("SceneShadowMap_QLo.t3fxb", "0")
    RenderPreloadShader("SceneShadowMapAlpha_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_1SKN_LGT_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "334")
    RenderPreloadShader("FX_Null_QLo.t3fxb", "0")
    RenderPreloadShader("DirectionalLightShadow_QLo.t3fxb", "1024")
    RenderPreloadShader("SceneToonOutline2_CC_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_LGT_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_QLo.t3fxb", "199")
    RenderPreloadShader("ScenePreZ_QLo.t3fxb", "128")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "142")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "330")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "66")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "66")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "322")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_1SKN_LGT_CC_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "66")
    RenderPreloadShader("SceneShadowMapAlpha_1SKN_QLo.t3fxb", "0")
    RenderPreloadShader("SceneToonOutline2_1SKN_CC_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "68")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_TOON_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "323")
    RenderPreloadShader("SceneToonOutline2_CC_QLo.t3fxb", "320")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "194")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "194")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "194")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "202")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "202")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "202")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "195")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "195")
    RenderPreloadShader("Mesh_DTL_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_SDTL_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "330")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "72")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "330")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "72")
    RenderPreloadShader("Mesh_DTL_CC_QLo.t3fxb", "74")
    RenderPreloadShader("SceneToonOutline2_CC_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "266")
  end
end
function LodgeExteriorFront()
  Game_NewScene(kScene, kScript)
  Navigate_Enable(false)
  if LogicGet("3LodgeFront - Met Bonnie") == false and IsPlatformAndroid() then
    AgentSetProperty("cam_cutsceneChore", "Clip Plane - Near", 0.2)
  end
  PreloadAssets()
  if Game_GetDebug() and LogicGet("3LodgeFront - Zombies Surrounded") then
    Game_SetSceneDialog("env_lodgeExteriorFront_fight")
    Yield()
  end
  Game_StartScene(true)
end
function LodgeExteriorFront_ShootZombie()
  local zombieNum = LogicGet("3LodgeFront - Target Zombie")
  local zombie = AgentFind("Zombie" .. zombieNum)
  if not zombie.mShotChorePriority then
    zombie.mShotChorePriority = 100
  end
  local targetType = LogicGet("3LodgeFront - Target Type")
  if targetType == 3 then
    AgentSetProperty(zombie, kIdleAnim, "adv_lodgeExteriorFront_zombieDead.chore")
    AgentSetSelectable("obj_zombieHead" .. zombieNum, false)
    AgentSetProperty("trigger_zombieDeath" .. zombieNum, kTriggerEnabled, false)
  end
  local choreName = string.format("env_lodgeExteriorFront_fight_shootZombie%d_%d", zombieNum, targetType)
  ChorePlay(choreName, zombie.mShotChorePriority)
  zombie.mShotChorePriority = zombie.mShotChorePriority + 1
end
function LodgeExteriorFront_OnZombieTrigger(agent, trigger)
  if Game_IsPlayMode() or Game_GetMode() == eModeCutscene then
    Game_RunDialog(agent.mProps["Trigger - Dialog Node Enter"])
  end
end
SceneOpen(kScene, kScript)
