local kScript = "NextTimeOn"
local kScene = "adv_nextTimeOn202"
local PreloadAssets = function()
  if Platform_NeedShaderPreload() then
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "131")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "195")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "326")
    RenderPreloadShader("SceneToonOutline2_CC_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "195")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_CC_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_LGT_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_1SKN_CC_QLo.t3fxb", "327")
    RenderPreloadShader("SceneToonOutline2_CC_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_DTL_CC_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "327")
    RenderPreloadShader("SceneToonOutline2_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_DTL_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_LGT_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "256")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "4")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_TOON_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "334")
  end
end
function NextTimeOn()
  Game_NewScene(kScene, kScript)
  SaveLoad_SaveEventLog()
  Navigate_Enable(false)
  if IsPlatformAndroid() then
    AgentSetProperty("cam_cutsceneChore", "Clip Plane - Near", 0.135)
  end
  PreloadAssets()
  Game_StartScene(true)
end
function NextTimeOn_EndEpisode()
  WDAchievements_Unlock("achievement_08")
  SaveLoad_SetEpisode("ShowEndCredits2")
  Menu_EndStats(2)
  Game_EndEpisode("MenuSeason2", "Menu_Main")
end
SceneOpen(kScene, kScript)
SceneAdd("ui_nextTimeOn")
