--|||||||||||||||||||||||||||||||||||||||||||||||| INCLUDES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| INCLUDES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| INCLUDES ||||||||||||||||||||||||||||||||||||||||||||||||
--Here we include the relight include file, and this file will include all of the dependencies with the relight mod.
--This also includes the Telltale Lua Script Extensions (TLSE) backend as well with all of it's core files + development tools.

require("RELIGHT_Include.lua");

--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE SCENE VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE SCENE VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE SCENE VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--Here telltale declares these two variables at the top of every level script.
--NOTE: That we are only intrested in kScene which is a reference to the actual scene file.
--This is CRITICAL as getting a reference to it means we can do everything that we need to do in the scene.

local kScript = "RiverCamp"
local kScene = "adv_riverCamp"

--|||||||||||||||||||||||||||||||||||||||||||||||| CUSTOM VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| CUSTOM VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| CUSTOM VARIABLES ||||||||||||||||||||||||||||||||||||||||||||||||
--Here we declare our own variables related to Relight and Telltale Lua Script Extensions (TLSE) development tools.
--NOTE: These are declared globally so they can be used throughout all scripts.

--Telltale Lua Script Extensions (TLSE) Development variables
TLSE_Development_SceneObject = kScene;
TLSE_Development_SceneObjectAgentName = kScene .. ".scene";
TLSE_Development_FreecamUseFOVScale = false;

--Relight variables
RELIGHT_SceneObject = kScene;
RELIGHT_SceneObjectAgentName = kScene .. ".scene";
RelightConfigGlobal = RelightConfigData_Main.Global;
RelightConfigDevelopment = RelightConfigData_Development.DevelopmentTools;
--RelightConfigLevel = RelightConfigData_Season2.Level_202_LodgeMainRoom;

--Relight DOF
RELIGHT_DOF_AUTOFOCUS_UseCameraDOF = true;
RELIGHT_DOF_AUTOFOCUS_UseLegacyDOF = false;
RELIGHT_DOF_AUTOFOCUS_UseHighQualityDOF = true;
RELIGHT_DOF_AUTOFOCUS_FocalRange = 1.0;
RELIGHT_DOF_AUTOFOCUS_GameplayCameraNames = {};
RELIGHT_DOF_AUTOFOCUS_ObjectEntries = 
{
    "Clementine"
};
RELIGHT_DOF_AUTOFOCUS_Settings =
{
    TargetValidation_IsOnScreen = true,
    TargetValidation_IsVisible = true,
    TargetValidation_IsWithinDistance = true,
    TargetValidation_IsFacingCamera = true,
    TargetValidation_IsOccluded = false,
    TargetValidation_RejectionAngle = 0.0, --goes from -1 to 1 (less than 0 is within the 180 forward facing fov of the given object)
    TargetValidation_RejectionDistance = 40.0, --the max distance before the agent is too far from camera to do autofocus
};
RELIGHT_DOF_AUTOFOCUS_BokehSettings =
{
    BokehBrightnessDeltaThreshold = 0.02,
    BokehBrightnessThreshold = 0.02,
    BokehBlurThreshold = 0.05,
    BokehMinSize = 0.0,
    BokehMaxSize = 0.03,
    BokehFalloff = 0.75,
    MaxBokehBufferAmount = 1.0,
    BokehPatternTexture = "bokeh_circle.d3dtx"
};

--Relight Volumetrics
RELIGHT_HackyCameraVolumetrics_Settings = 
{
    Samples = 256,
    SampleOffset = 0.15,
    SampleStartOffset = 1.0,
    FogColor = Color(0.1, 0.1, 0.1, 0.1)
};

--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE LEVEL LOGIC ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE LEVEL LOGIC ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| TELLTALE LEVEL LOGIC ||||||||||||||||||||||||||||||||||||||||||||||||
--Here is alot of the original (decompiled) telltale lua script logic for the level.
--We are leaving this untouched because we still want the level to function normally as intended.

local mHolesInCan = 0
local mTimerID, mTimerController
local mTimerPercent = 0

local PreloadAssets = function()
  if Platform_NeedShaderPreload() then
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "76")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "8")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "263")
    RenderPreloadShader("SceneToonOutline2_1SKN_CC_TONE_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "264")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "264")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "4")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_DTL_CC_TONE_SDTL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "8")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "2")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "334")
    RenderPreloadShader("SceneToonOutline2_CC_TONE_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "66")
    RenderPreloadShader("Mesh_DTL_CC_TONE_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "135")
    RenderPreloadShader("SceneShadowMap_VCOL_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "2")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "323")
    RenderPreloadShader("SceneToonOutline2_CC_TONE_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "68")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_DTL_CC_TONE_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "72")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "66")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_DTL_CC_TONE_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_VCOL_CC_TONE_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "328")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "328")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TONE_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "194")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "195")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "322")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("SceneToonOutline2_1SKN_CC_TINT_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "68")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_TINT_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "320")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_TOON_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_TOON_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("SceneToonOutline2_1SKN_CC_TINT_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "4")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_TINT_SDTL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_TINT_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_DTL_CC_TINT_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "4")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_ENV_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "256")
    RenderPreloadShader("Mesh_TOON_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_TOON_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_ENV_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "68")
  end
  PreLoad("adv_everywhere_clementine200.chore")
  PreLoad("adv_riverCamp.chore")
  PreLoad("adv_riverCamp.prop")
  PreLoad("adv_riverCamp.scene")
  PreLoad("adv_riverCamp.wbox")
  PreLoad("adv_riverCamp_camDogFightDrift.chore")
  PreLoad("adv_riverCamp_camDogFightDriftMore.chore")
  PreLoad("adv_riverCamp_camZombieSmashDrift.chore")
  PreLoad("adv_riverCamp_clemFightDogCanCenter.chore")
  PreLoad("adv_riverCamp_clemFightDogCenter.chore")
  PreLoad("adv_riverCamp_clemFightDogKnifeCenter.chore")
  PreLoad("adv_riverCamp_clemFightDogLeft.chore")
  PreLoad("adv_riverCamp_clemFightDogLeftCan.chore")
  PreLoad("adv_riverCamp_clemFightDogRight.chore")
  PreLoad("adv_riverCamp_dogSniffAroundCamp.chore")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillC.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillC.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillC.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillE.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillE.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesHillE.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesI.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesI.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesI.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesK.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesK.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesK.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesL.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesL.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesL.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesM.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesM.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesM.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesN.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesN.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesN.skl")
  PreLoad("adv_riverCamp_foliageBrushmeshesO.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushmeshesO.prop")
  PreLoad("adv_riverCamp_foliageBrushmeshesO.skl")
  PreLoad("adv_riverCamp_foliageBrushmeshesP.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushmeshesP.prop")
  PreLoad("adv_riverCamp_foliageBrushmeshesP.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesQ.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesQ.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesQ.skl")
  PreLoad("adv_riverCamp_foliageBrushMeshesWoodedB.d3dmesh")
  PreLoad("adv_riverCamp_foliageBrushMeshesWoodedB.prop")
  PreLoad("adv_riverCamp_foliageBrushMeshesWoodedB.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillB.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillB.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillB.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillD.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillD.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesHillD.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesI.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesI.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesI.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesK.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesK.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesK.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesL.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesL.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesL.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesM.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesM.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesM.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesN.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesN.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesN.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesO.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesO.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesO.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesP.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesP.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesP.skl")
  PreLoad("adv_riverCamp_foliageTreeMeshesWoodedB.d3dmesh")
  PreLoad("adv_riverCamp_foliageTreeMeshesWoodedB.prop")
  PreLoad("adv_riverCamp_foliageTreeMeshesWoodedB.skl")
  PreLoad("adv_riverCamp_meshesA.d3dmesh")
  PreLoad("adv_riverCamp_meshesA.prop")
  PreLoad("adv_riverCamp_meshesB.d3dmesh")
  PreLoad("adv_riverCamp_meshesB.prop")
  PreLoad("adv_riverCamp_meshesC.d3dmesh")
  PreLoad("adv_riverCamp_meshesC.prop")
  PreLoad("adv_riverCamp_meshesD.d3dmesh")
  PreLoad("adv_riverCamp_meshesD.prop")
  PreLoad("adv_riverCamp_meshesE.d3dmesh")
  PreLoad("adv_riverCamp_meshesE.prop")
  PreLoad("adv_riverCamp_meshesF.d3dmesh")
  PreLoad("adv_riverCamp_meshesF.prop")
  PreLoad("adv_riverCamp_meshesG.d3dmesh")
  PreLoad("adv_riverCamp_meshesG.prop")
  PreLoad("adv_riverCamp_meshesH.d3dmesh")
  PreLoad("adv_riverCamp_meshesH.prop")
  PreLoad("adv_riverCamp_meshesHillA.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillA.prop")
  PreLoad("adv_riverCamp_meshesHillB.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillB.prop")
  PreLoad("adv_riverCamp_meshesHillC.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillC.prop")
  PreLoad("adv_riverCamp_meshesHillD.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillD.prop")
  PreLoad("adv_riverCamp_meshesHillE.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillE.prop")
  PreLoad("adv_riverCamp_meshesHillF.d3dmesh")
  PreLoad("adv_riverCamp_meshesHillF.prop")
  PreLoad("adv_riverCamp_meshesI.d3dmesh")
  PreLoad("adv_riverCamp_meshesI.prop")
  PreLoad("adv_riverCamp_meshesJ.d3dmesh")
  PreLoad("adv_riverCamp_meshesJ.prop")
  PreLoad("adv_riverCamp_meshesK.d3dmesh")
  PreLoad("adv_riverCamp_meshesK.prop")
  PreLoad("adv_riverCamp_meshesL.d3dmesh")
  PreLoad("adv_riverCamp_meshesL.prop")
  PreLoad("adv_riverCamp_meshesM.d3dmesh")
  PreLoad("adv_riverCamp_meshesM.prop")
  PreLoad("adv_riverCamp_meshesN.d3dmesh")
  PreLoad("adv_riverCamp_meshesN.prop")
  PreLoad("adv_riverCamp_meshesP.d3dmesh")
  PreLoad("adv_riverCamp_meshesP.prop")
  PreLoad("adv_riverCamp_meshesQ.d3dmesh")
  PreLoad("adv_riverCamp_meshesQ.prop")
  PreLoad("adv_riverCamp_meshesWoodedA.d3dmesh")
  PreLoad("adv_riverCamp_meshesWoodedA.prop")
  PreLoad("adv_riverCamp_meshesWoodedB.d3dmesh")
  PreLoad("adv_riverCamp_meshesWoodedB.prop")
  PreLoad("adv_riverCamp_meshesWoodedC.d3dmesh")
  PreLoad("adv_riverCamp_meshesWoodedC.prop")
  PreLoad("adv_riverCamp_zombieIdle.chore")
  PreLoad("amb_cabin_exterior_forest_wind.wav")
  PreLoad("bg_blank.chore")
  PreLoad("cam_camCutscene_driftExtreme_add.anm")
  PreLoad("cam_camCutscene_driftSlow_add.anm")
  PreLoad("cam_cutscene_sk38_action_dogWDKillsClem.anm")
  PreLoad("cam_cutscene_sk38_action_dogWDLetsGoOfClem.anm")
  PreLoad("cam_cutscene_sk56_action_clem200KicksDog.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteHoldCan_hitDog.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteHoldKnife_stabDog.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteStruggleLeft_toDogBiteStruggle.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteStruggle_toDogBiteStruggleLeft.anm")
  PreLoad("cam_cutscene_sk56_clementine200DogBiteStruggle_toDogBiteStruggleRight.anm")
  PreLoad("cam_cutscene_sk56_idle_clementine200DogBiteHoldCan.anm")
  PreLoad("cam_cutscene_sk56_idle_clementine200DogBiteHoldKnife.anm")
  PreLoad("cam_cutscene_sk56_idle_clementine200DogBiteStruggle.anm")
  PreLoad("cam_cutscene_sk56_idle_clementine200DogBiteStruggleLeft.anm")
  PreLoad("cam_cutscene_sk56_idle_clementine200DogBiteStruggleRight.anm")
  PreLoad("cam_dogFight_horizontal_adv_riverCamp.chore")
  PreLoad("cam_dogFight_vertical_adv_riverCamp.chore")
  PreLoad("cam_nav_barrel_horizontal_adv_riverCamp.chore")
  PreLoad("cam_nav_barrel_vertical_adv_riverCamp.chore")
  PreLoad("can_stir_food_1.wav")
  PreLoad("can_stir_food_2.wav")
  PreLoad("can_stir_food_3.wav")
  PreLoad("chorebox_riverCamp_camNavBarrel_depth.chore")
  PreLoad("chorebox_riverCamp_camNavCamp_depth.chore")
  PreLoad("chorebox_riverCamp_camNavCooler_depth.chore")
  PreLoad("chorebox_riverCamp_camNavVan_depth.chore")
  PreLoad("clementine200_eyes_lookDown_add.anm")
  PreLoad("clementine200_eyes_lookLeft_add.anm")
  PreLoad("clementine200_eyes_lookRight_add.anm")
  PreLoad("clementine200_eyes_lookUp_add.anm")
  PreLoad("clementine200_face_blink.anm")
  PreLoad("clementine200_face_blink_add.anm")
  PreLoad("clementine200_face_browsDownGesture_add.anm")
  PreLoad("clementine200_face_browsUpFastGesture_add.anm")
  PreLoad("clementine200_face_eyesDartsA_add.anm")
  PreLoad("clementine200_face_eyesDartsB_add.anm")
  PreLoad("clementine200_face_eyesDartsC_add.anm")
  PreLoad("clementine200_face_eyesWide_add.anm")
  PreLoad("clementine200_face_squint_add.anm")
  PreLoad("clementine200_headGesture_lookDown_add.anm")
  PreLoad("clementine200_headGesture_lookDown_add.chore")
  PreLoad("clementine200_headGesture_lookLeft_add.anm")
  PreLoad("clementine200_headGesture_lookLeft_add.chore")
  PreLoad("clementine200_headGesture_lookRight_add.anm")
  PreLoad("clementine200_headGesture_lookRight_add.chore")
  PreLoad("clementine200_headGesture_lookUp_add.anm")
  PreLoad("clementine200_headGesture_lookUp_add.chore")
  PreLoad("clementine200_headGesture_tiltLeftA_add.anm")
  PreLoad("clementine200_headGesture_tiltLeftB_add.anm")
  PreLoad("clementine200_headGesture_tiltRightA_add.anm")
  PreLoad("clementine200_headGesture_tiltRightB_add.anm")
  PreLoad("clementine200_phoneme_AA.anm")
  PreLoad("clementine200_phoneme_AA_fearB.anm")
  PreLoad("clementine200_phoneme_AA_fearC.anm")
  PreLoad("clementine200_phoneme_AA_fearCX.anm")
  PreLoad("clementine200_phoneme_AA_normalA.anm")
  PreLoad("clementine200_phoneme_AA_painA.anm")
  PreLoad("clementine200_phoneme_AA_painAX.anm")
  PreLoad("clementine200_phoneme_AA_thinkingA.anm")
  PreLoad("clementine200_phoneme_AA_thinkingB.anm")
  PreLoad("clementine200_phoneme_default.anm")
  PreLoad("clementine200_phoneme_default_fearB.anm")
  PreLoad("clementine200_phoneme_default_fearC.anm")
  PreLoad("clementine200_phoneme_default_fearCX.anm")
  PreLoad("clementine200_phoneme_default_normalA.anm")
  PreLoad("clementine200_phoneme_default_painA.anm")
  PreLoad("clementine200_phoneme_default_painAX.anm")
  PreLoad("clementine200_phoneme_default_thinkingA.anm")
  PreLoad("clementine200_phoneme_default_thinkingB.anm")
  PreLoad("clementine200_phoneme_EE.anm")
  PreLoad("clementine200_phoneme_EE_fearB.anm")
  PreLoad("clementine200_phoneme_EE_fearC.anm")
  PreLoad("clementine200_phoneme_EE_fearCX.anm")
  PreLoad("clementine200_phoneme_EE_normalA.anm")
  PreLoad("clementine200_phoneme_EE_painA.anm")
  PreLoad("clementine200_phoneme_EE_painAX.anm")
  PreLoad("clementine200_phoneme_EE_painD.anm")
  PreLoad("clementine200_phoneme_EE_thinkingA.anm")
  PreLoad("clementine200_phoneme_EE_thinkingB.anm")
  PreLoad("clementine200_phoneme_FV.anm")
  PreLoad("clementine200_phoneme_FV_fearB.anm")
  PreLoad("clementine200_phoneme_FV_fearC.anm")
  PreLoad("clementine200_phoneme_FV_fearCX.anm")
  PreLoad("clementine200_phoneme_FV_normalA.anm")
  PreLoad("clementine200_phoneme_FV_painA.anm")
  PreLoad("clementine200_phoneme_FV_painAX.anm")
  PreLoad("clementine200_phoneme_FV_thinkingA.anm")
  PreLoad("clementine200_phoneme_FV_thinkingB.anm")
  PreLoad("clementine200_phoneme_I.anm")
  PreLoad("clementine200_phoneme_I_fearB.anm")
  PreLoad("clementine200_phoneme_I_fearC.anm")
  PreLoad("clementine200_phoneme_I_fearCX.anm")
  PreLoad("clementine200_phoneme_I_normalA.anm")
  PreLoad("clementine200_phoneme_I_painA.anm")
  PreLoad("clementine200_phoneme_I_painAX.anm")
  PreLoad("clementine200_phoneme_I_thinkingA.anm")
  PreLoad("clementine200_phoneme_I_thinkingB.anm")
  PreLoad("clementine200_phoneme_LL.anm")
  PreLoad("clementine200_phoneme_LL_fearB.anm")
  PreLoad("clementine200_phoneme_LL_fearC.anm")
  PreLoad("clementine200_phoneme_LL_fearCX.anm")
  PreLoad("clementine200_phoneme_LL_normalA.anm")
  PreLoad("clementine200_phoneme_LL_painA.anm")
  PreLoad("clementine200_phoneme_LL_painAX.anm")
  PreLoad("clementine200_phoneme_LL_thinkingA.anm")
  PreLoad("clementine200_phoneme_LL_thinkingB.anm")
  PreLoad("clementine200_phoneme_MM.anm")
  PreLoad("clementine200_phoneme_MM_fearB.anm")
  PreLoad("clementine200_phoneme_MM_fearC.anm")
  PreLoad("clementine200_phoneme_MM_fearCX.anm")
  PreLoad("clementine200_phoneme_MM_normalA.anm")
  PreLoad("clementine200_phoneme_MM_painA.anm")
  PreLoad("clementine200_phoneme_MM_painAX.anm")
  PreLoad("clementine200_phoneme_MM_sadCX.anm")
  PreLoad("clementine200_phoneme_MM_thinkingA.anm")
  PreLoad("clementine200_phoneme_MM_thinkingB.anm")
  PreLoad("clementine200_phoneme_NN.anm")
  PreLoad("clementine200_phoneme_NN_fearB.anm")
  PreLoad("clementine200_phoneme_NN_fearC.anm")
  PreLoad("clementine200_phoneme_NN_fearCX.anm")
  PreLoad("clementine200_phoneme_NN_normalA.anm")
  PreLoad("clementine200_phoneme_NN_painA.anm")
  PreLoad("clementine200_phoneme_NN_painAX.anm")
  PreLoad("clementine200_phoneme_NN_thinkingA.anm")
  PreLoad("clementine200_phoneme_NN_thinkingB.anm")
  PreLoad("clementine200_phoneme_O.anm")
  PreLoad("clementine200_phoneme_O_fearB.anm")
  PreLoad("clementine200_phoneme_O_fearC.anm")
  PreLoad("clementine200_phoneme_O_fearCX.anm")
  PreLoad("clementine200_phoneme_O_normalA.anm")
  PreLoad("clementine200_phoneme_O_painA.anm")
  PreLoad("clementine200_phoneme_O_painAX.anm")
  PreLoad("clementine200_phoneme_O_thinkingA.anm")
  PreLoad("clementine200_phoneme_O_thinkingB.anm")
  PreLoad("clementine200_phoneme_SH.anm")
  PreLoad("clementine200_phoneme_SH_fearB.anm")
  PreLoad("clementine200_phoneme_SH_fearC.anm")
  PreLoad("clementine200_phoneme_SH_fearCX.anm")
  PreLoad("clementine200_phoneme_SH_normalA.anm")
  PreLoad("clementine200_phoneme_SH_painA.anm")
  PreLoad("clementine200_phoneme_SH_painAX.anm")
  PreLoad("clementine200_phoneme_SH_thinkingA.anm")
  PreLoad("clementine200_phoneme_SH_thinkingB.anm")
  PreLoad("clementine200_phoneme_TH.anm")
  PreLoad("clementine200_phoneme_TH_fearB.anm")
  PreLoad("clementine200_phoneme_TH_fearC.anm")
  PreLoad("clementine200_phoneme_TH_fearCX.anm")
  PreLoad("clementine200_phoneme_TH_normalA.anm")
  PreLoad("clementine200_phoneme_TH_painA.anm")
  PreLoad("clementine200_phoneme_TH_painAX.anm")
  PreLoad("clementine200_phoneme_TH_thinkingA.anm")
  PreLoad("clementine200_phoneme_TH_thinkingB.anm")
  PreLoad("clementine200_phoneme_U.anm")
  PreLoad("clementine200_phoneme_U_fearB.anm")
  PreLoad("clementine200_phoneme_U_fearC.anm")
  PreLoad("clementine200_phoneme_U_fearCX.anm")
  PreLoad("clementine200_phoneme_U_normalA.anm")
  PreLoad("clementine200_phoneme_U_painA.anm")
  PreLoad("clementine200_phoneme_U_painAX.anm")
  PreLoad("clementine200_phoneme_U_thinkingA.anm")
  PreLoad("clementine200_phoneme_U_thinkingB.anm")
  PreLoad("clementine_face_blink.chore")
  PreLoad("clementine_face_default.chore")
  PreLoad("clementine_face_default_eyes.chore")
  PreLoad("clementine_lookAt_head.chore")
  PreLoad("clothing_scuffle_medium_1.wav")
  PreLoad("clothing_soft_2.wav")
  PreLoad("color_000.d3dtx")
  PreLoad("color_666666.d3dtx")
  PreLoad("color_FFFFFF.d3dtx")
  PreLoad("comp_violence_zombie_8.wav")
  PreLoad("comp_violence_zombie_9.wav")
  PreLoad("Death.imap")
  PreLoad("dogWD_face_default.anm")
  PreLoad("dogWD_headGesture_lookLeft.anm")
  PreLoad("dogWD_headGesture_lookRight.anm")
  PreLoad("dogWD_headGesture_lookUp_add.anm")
  PreLoad("dogWD_headGesture_sniff.anm")
  PreLoad("dog_angry_bark_13.wav")
  PreLoad("dog_angry_bark_2.wav")
  PreLoad("dog_angry_growl_2.wav")
  PreLoad("dog_angry_growl_lp.wav")
  PreLoad("dog_attack_1.wav")
  PreLoad("dog_attack_10.wav")
  PreLoad("dog_attack_11.wav")
  PreLoad("dog_attack_2.wav")
  PreLoad("dog_attack_3.wav")
  PreLoad("dog_attack_4.wav")
  PreLoad("dog_attack_5.wav")
  PreLoad("dog_attack_6.wav")
  PreLoad("dog_attack_7.wav")
  PreLoad("dog_attack_8.wav")
  PreLoad("dog_eyes_lookAtsOff.chore")
  PreLoad("dog_face_default.chore")
  PreLoad("dog_fs_1.wav")
  PreLoad("dog_fs_2.wav")
  PreLoad("dog_fs_3.wav")
  PreLoad("dog_fs_4.wav")
  PreLoad("dog_fs_5.wav")
  PreLoad("dog_fs_6.wav")
  PreLoad("dog_fs_7.wav")
  PreLoad("dog_fs_8.wav")
  PreLoad("dog_growl_close_1.wav")
  PreLoad("dog_growl_close_2.wav")
  PreLoad("dog_growl_close_3.wav")
  PreLoad("dog_whine_1.wav")
  PreLoad("dog_whine_2.wav")
  PreLoad("dog_whine_3.wav")
  PreLoad("dog_whine_4.wav")
  PreLoad("dog_whine_5.wav")
  PreLoad("dog_whine_6.wav")
  PreLoad("dog_whine_8.wav")
  PreLoad("dog_whine_sniff.wav")
  PreLoad("dog_yelp_1.wav")
  PreLoad("env_birdNestPieces.d3dtx")
  PreLoad("env_branchPineRiverCampA.d3dtx")
  PreLoad("env_branchPineRiverWoodsA.d3dtx")
  PreLoad("env_bushLightRiverWoodsA.d3dtx")
  PreLoad("env_bushRiverCamptA_alpha.d3dtx")
  PreLoad("env_bushUnderwaterWoodsA.d3dtx")
  PreLoad("env_cabinExtCurtainsA.d3dtx")
  PreLoad("env_cabinExtDoors.d3dtx")
  PreLoad("env_cabinExtGlassFrontDoor.d3dtx")
  PreLoad("env_cabinExtMoldingsA.d3dtx")
  PreLoad("env_cabinExtMoldingsB.d3dtx")
  PreLoad("env_cabinExtMoldingsC.d3dtx")
  PreLoad("env_cabinExtMoldingsD.d3dtx")
  PreLoad("env_cabinExtMoldingsE.d3dtx")
  PreLoad("env_cabinExtMoldingsF.d3dtx")
  PreLoad("env_clementineHouseInteriorStairsBottom.d3dtx")
  PreLoad("env_clementineHouseInteriorTrashcan.d3dtx")
  PreLoad("env_drugstoreExtWindowsDestroyed_alpha.d3dtx")
  PreLoad("env_drugstoreOfficeCalendar.d3dtx")
  PreLoad("env_drugstoreOfficeSetDressItems.d3dtx")
  PreLoad("env_drugstoreOfficeSignboardPapers.d3dtx")
  PreLoad("env_fernRiverCamp.d3dtx")
  PreLoad("env_FoliageBrush_idle.anm")
  PreLoad("env_FoliageTrees_idle.anm")
  PreLoad("env_forestWaterTowerBushBgB.d3dtx")
  PreLoad("env_grassBearTrapWoods.d3dtx")
  PreLoad("env_grassHIRiverWoods.d3dtx")
  PreLoad("env_grassRiverCampWalk.d3dtx")
  PreLoad("env_grassRiverWoodsA.d3dtx")
  PreLoad("env_grassTuftRiverWoodsA.d3dtx")
  PreLoad("env_leavesHighRiverCamp.d3dtx")
  PreLoad("env_logEdgeRiverCamp.d3dtx")
  PreLoad("env_logEdgeRiverWoods.d3dtx")
  PreLoad("env_logHollowClearingCampfire.d3dtx")
  PreLoad("env_manorInteriorPortraits.d3dtx")
  PreLoad("env_riverCamp.dlog")
  PreLoad("env_riverCamp_bg_deathTimer_1.chore")
  PreLoad("env_riverCamp_cs_dogAttacks_1.chore")
  PreLoad("env_riverCamp_cs_dogDeath_1.chore")
  PreLoad("env_riverCamp_cs_dogDeath_2.chore")
  PreLoad("env_riverCamp_cs_dogFightCenterLeftCan_1.chore")
  PreLoad("env_riverCamp_cs_dogFightCenterLeft_1.chore")
  PreLoad("env_riverCamp_cs_dogFightCenterRight_1.chore")
  PreLoad("env_riverCamp_cs_dogFightLeftCenterCan_1.chore")
  PreLoad("env_riverCamp_cs_dogLetsGoCan_1.chore")
  PreLoad("env_riverCamp_cs_dogLetsGoKnife_1.chore")
  PreLoad("env_riverCamp_cs_dogLetsGo_1.chore")
  PreLoad("env_riverCamp_cs_kickDog_1.chore")
  PreLoad("env_riverCamp_use_can_1.chore")
  PreLoad("env_riverCamp_use_dogFight_1.chore")
  PreLoad("env_riverCamp_use_dogFight_10.chore")
  PreLoad("env_riverCamp_use_dogFight_2.chore")
  PreLoad("env_riverCamp_use_dogFight_3.chore")
  PreLoad("env_riverCamp_use_dogFight_4.chore")
  PreLoad("env_riverCamp_use_dogFight_5.chore")
  PreLoad("env_riverCamp_use_dogFight_6.chore")
  PreLoad("env_riverCamp_use_dogFight_7.chore")
  PreLoad("env_riverCamp_use_dogFight_8.chore")
  PreLoad("env_riverCamp_use_knife_5.chore")
  PreLoad("env_riverWoodsBushBaseA.d3dtx")
  PreLoad("env_riverWoodsBushBaseB.d3dtx")
  PreLoad("env_riverWoodsBushBaseC.d3dtx")
  PreLoad("env_riverWoodsDeadTreeImpale.d3dtx")
  PreLoad("env_riverWoodsGroundCoverA.d3dtx")
  PreLoad("env_rockInkworkCabinExterior.d3dtx")
  PreLoad("env_rockInkworkMossy.d3dtx")
  PreLoad("env_treePineFlatRiverWoodsBase.d3dtx")
  PreLoad("env_treesPineRimA.d3dtx")
  PreLoad("env_treesPineRimBase.d3dtx")
  PreLoad("Fight_fist_swing_07.wav")
  PreLoad("Fight_fist_swing_10.wav")
  PreLoad("Fight_foot_swing_06.wav")
  PreLoad("flies_lp.wav")
  PreLoad("flies_lp_2.wav")
  PreLoad("fol_bodyfall_04.wav")
  PreLoad("fol_bodyfall_dirt_02.wav")
  PreLoad("fol_bodyfall_dirt_03.wav")
  PreLoad("fol_branch_movement_01.wav")
  PreLoad("fol_branch_movement_02.wav")
  PreLoad("fol_branch_movement_04.wav")
  PreLoad("fol_branch_movement_05.wav")
  PreLoad("fol_branch_movement_06.wav")
  PreLoad("fol_hands_grab_muted_7.wav")
  PreLoad("fol_machette_chop_branch_01.wav")
  PreLoad("fol_machette_chop_branch_03.wav")
  PreLoad("fol_machette_chop_branch_05.wav")
  PreLoad("fol_metal_creak_long_1.wav")
  PreLoad("fol_metal_creak_long_2.wav")
  PreLoad("fol_swoosh_clothes.wav")
  PreLoad("fol_tin_can_4.wav")
  PreLoad("fs_grass_tall_1.wav")
  PreLoad("fs_grass_tall_2.wav")
  PreLoad("fs_grass_tall_3.wav")
  PreLoad("fs_grass_tall_4.wav")
  PreLoad("fs_grass_tall_5.wav")
  PreLoad("fs_zomb_scrape_drag_19.wav")
  PreLoad("fx_bloodPoolRadialA.d3dmesh")
  PreLoad("fx_bloodPoolRadialA.d3dtx")
  PreLoad("fx_bloodPoolRadialA.prop")
  PreLoad("fx_bloodSplatDirAvgA.d3dmesh")
  PreLoad("fx_bloodSplatDirAvgA.prop")
  PreLoad("fx_bloodSplatDirAvgA1.d3dtx")
  PreLoad("fx_bloodSplatDirAvgB.d3dmesh")
  PreLoad("fx_bloodSplatDirAvgB.prop")
  PreLoad("fx_bloodSplatDirAvgB1.d3dtx")
  PreLoad("fx_bloodSplatDirAvgC.d3dmesh")
  PreLoad("fx_bloodSplatDirAvgC.d3dtx")
  PreLoad("fx_bloodSplatDirAvgC.prop")
  PreLoad("fx_bloodSplatDirAvgD.d3dmesh")
  PreLoad("fx_bloodSplatDirAvgD.d3dtx")
  PreLoad("fx_bloodSplatDirAvgD.prop")
  PreLoad("fx_bloodSplatDirNrwA.d3dmesh")
  PreLoad("fx_bloodSplatDirNrwA.d3dtx")
  PreLoad("fx_bloodSplatDirNrwA.prop")
  PreLoad("fx_bloodSplatDirNrwB.d3dmesh")
  PreLoad("fx_bloodSplatDirNrwB.prop")
  PreLoad("fx_bloodSplatDirNrwB1.d3dtx")
  PreLoad("fx_bloodSplatDirNrwC.d3dmesh")
  PreLoad("fx_bloodSplatDirNrwC.d3dtx")
  PreLoad("fx_bloodSplatDirNrwC.prop")
  PreLoad("fx_bloodSplatDirNrwD.d3dmesh")
  PreLoad("fx_bloodSplatDirNrwD.d3dtx")
  PreLoad("fx_bloodSplatDirNrwD.prop")
  PreLoad("fx_bloodSplatDirWdeA.d3dmesh")
  PreLoad("fx_bloodSplatDirWdeA.d3dtx")
  PreLoad("fx_bloodSplatDirWdeA.prop")
  PreLoad("fx_bloodSplatDirWdeB.d3dmesh")
  PreLoad("fx_bloodSplatDirWdeB.prop")
  PreLoad("fx_bloodSplatDirWdeB1.d3dtx")
  PreLoad("fx_bloodSplatDirWdeC.d3dmesh")
  PreLoad("fx_bloodSplatDirWdeC.d3dtx")
  PreLoad("fx_bloodSplatDirWdeC.prop")
  PreLoad("fx_bloodSplatDirWdeD.d3dmesh")
  PreLoad("fx_bloodSplatDirWdeD.d3dtx")
  PreLoad("fx_bloodSplatDirWdeD.prop")
  PreLoad("fx_bloodSplatRadA.d3dmesh")
  PreLoad("fx_bloodSplatRadA.d3dtx")
  PreLoad("fx_bloodSplatRadA.prop")
  PreLoad("fx_bloodSplatRadB.d3dmesh")
  PreLoad("fx_bloodSplatRadB.d3dtx")
  PreLoad("fx_bloodSplatRadB.prop")
  PreLoad("fx_bloodSplatRadC.d3dmesh")
  PreLoad("fx_bloodSplatRadC.d3dtx")
  PreLoad("fx_bloodSplatRadC.prop")
  PreLoad("fx_bloodSplatRadD.d3dmesh")
  PreLoad("fx_bloodSplatRadD.prop")
  PreLoad("fx_bloodSplatRadD1.d3dtx")
  PreLoad("fx_bloodSplats201.scene")
  PreLoad("fx_bloodSpurtDirAvgA.d3dmesh")
  PreLoad("fx_bloodSpurtDirAvgA.d3dtx")
  PreLoad("fx_bloodSpurtDirAvgA.prop")
  PreLoad("fx_bloodSpurtDirAvgB.d3dmesh")
  PreLoad("fx_bloodSpurtDirAvgB.d3dtx")
  PreLoad("fx_bloodSpurtDirAvgB.prop")
  PreLoad("fx_bloodSpurtDirAvgC.d3dmesh")
  PreLoad("fx_bloodSpurtDirAvgC.d3dtx")
  PreLoad("fx_bloodSpurtDirAvgC.prop")
  PreLoad("fx_bloodSpurtDirAvgD.d3dmesh")
  PreLoad("fx_bloodSpurtDirAvgD.d3dtx")
  PreLoad("fx_bloodSpurtDirAvgD.prop")
  PreLoad("fx_bloodSpurtDirAvgE.d3dmesh")
  PreLoad("fx_bloodSpurtDirAvgE.d3dtx")
  PreLoad("fx_bloodSpurtDirAvgE.prop")
  PreLoad("fx_bloodSpurtDirNrwA.d3dmesh")
  PreLoad("fx_bloodSpurtDirNrwA.d3dtx")
  PreLoad("fx_bloodSpurtDirNrwA.prop")
  PreLoad("fx_bloodSpurtDirNrwB.d3dmesh")
  PreLoad("fx_bloodSpurtDirNrwB.d3dtx")
  PreLoad("fx_bloodSpurtDirNrwB.prop")
  PreLoad("fx_bloodSpurtDirNrwC.d3dmesh")
  PreLoad("fx_bloodSpurtDirNrwC.d3dtx")
  PreLoad("fx_bloodSpurtDirNrwC.prop")
  PreLoad("fx_bloodSpurtDirNrwD.d3dmesh")
  PreLoad("fx_bloodSpurtDirNrwD.d3dtx")
  PreLoad("fx_bloodSpurtDirNrwD.prop")
  PreLoad("fx_bloodSpurtDirRadBurst.d3dmesh")
  PreLoad("fx_bloodSpurtDirRadBurst.d3dtx")
  PreLoad("fx_bloodSpurtDirRadBurst.prop")
  PreLoad("fx_bloodSpurtDirWdeA.d3dmesh")
  PreLoad("fx_bloodSpurtDirWdeA.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeA.prop")
  PreLoad("fx_bloodSpurtDirWdeB.d3dmesh")
  PreLoad("fx_bloodSpurtDirWdeB.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeB.prop")
  PreLoad("fx_bloodSpurtDirWdeC.d3dmesh")
  PreLoad("fx_bloodSpurtDirWdeC.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeC.prop")
  PreLoad("fx_bloodSpurtDirWdeD.d3dmesh")
  PreLoad("fx_bloodSpurtDirWdeD.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeD.prop")
  PreLoad("fx_bloodSpurtDirWdeE.d3dmesh")
  PreLoad("fx_bloodSpurtDirWdeE.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeE.prop")
  PreLoad("fx_bloodSpurtEmitters201.scene")
  PreLoad("fx_bloodSpurtRadA.d3dmesh")
  PreLoad("fx_bloodSpurtRadA.d3dtx")
  PreLoad("fx_bloodSpurtRadA.prop")
  PreLoad("fx_bloodSpurtRadB.d3dmesh")
  PreLoad("fx_bloodSpurtRadB.d3dtx")
  PreLoad("fx_bloodSpurtRadB.prop")
  PreLoad("fx_bloodSpurtRadC.d3dmesh")
  PreLoad("fx_bloodSpurtRadC.d3dtx")
  PreLoad("fx_bloodSpurtRadC.prop")
  PreLoad("fx_bloodSpurtRadD.d3dmesh")
  PreLoad("fx_bloodSpurtRadD.d3dtx")
  PreLoad("fx_bloodSpurtRadD.prop")
  PreLoad("fx_bloodSpurtRadE.d3dmesh")
  PreLoad("fx_bloodSpurtRadE.d3dtx")
  PreLoad("fx_bloodSpurtRadE.prop")
  PreLoad("fx_bloodSpurtRadEmitterA.prop")
  PreLoad("fx_bloodSpurtRadEmitter_idleA.chore")
  PreLoad("fx_bloodSpurtRadE_emitter.chore")
  PreLoad("fx_bloodSpurtRadE_emitterAltU.chore")
  PreLoad("fx_bloodSpurtRadE_emitterAltV.chore")
  PreLoad("fx_bloodSpurtRadF.d3dmesh")
  PreLoad("fx_bloodSpurtRadF.d3dtx")
  PreLoad("fx_bloodSpurtRadF.prop")
  PreLoad("fx_bloodSpurtRadF_emitter.chore")
  PreLoad("fx_bloodSpurtRadF_emitterAltU.chore")
  PreLoad("fx_bloodSpurtRadF_emitterAltV.chore")
  PreLoad("fx_bloodSpurtRadG.d3dmesh")
  PreLoad("fx_bloodSpurtRadG.d3dtx")
  PreLoad("fx_bloodSpurtRadG.prop")
  PreLoad("fx_bloodSpurtRadG_emitter.chore")
  PreLoad("fx_bloodSpurtRadG_emitterAltU.chore")
  PreLoad("fx_bloodSpurtRadG_emitterAltV.chore")
  PreLoad("fx_bloodSpurtRadH.d3dmesh")
  PreLoad("fx_bloodSpurtRadH.d3dtx")
  PreLoad("fx_bloodSpurtRadH.prop")
  PreLoad("fx_bloodSpurtRadH_emitter.chore")
  PreLoad("fx_bloodSpurtRadH_emitterAltU.chore")
  PreLoad("fx_bloodSpurtRadH_emitterAltV.chore")
  PreLoad("fx_bloodSpurtRadI.d3dmesh")
  PreLoad("fx_bloodSpurtRadI.d3dtx")
  PreLoad("fx_bloodSpurtRadI.prop")
  PreLoad("fx_bloodSpurtRadI_emitter.chore")
  PreLoad("fx_bloodSpurtRadI_emitterAltU.chore")
  PreLoad("fx_bloodSpurtRadJ.d3dmesh")
  PreLoad("fx_bloodSpurtRadJ.d3dtx")
  PreLoad("fx_bloodSpurtRadJ.prop")
  PreLoad("fx_bloodSpurts201.scene")
  PreLoad("fx_flyWD.d3dmesh")
  PreLoad("fx_flyWD.d3dtx")
  PreLoad("fx_flyWD.prop")
  PreLoad("fx_flyWDEmitter.prop")
  PreLoad("fx_flyWD_fly1.anm")
  PreLoad("fx_flyWD_fly1.chore")
  PreLoad("fx_flyWD_fly2.chore")
  PreLoad("fx_overlayEyesBlink.d3dmesh")
  PreLoad("fx_overlayEyesBlink.d3dtx")
  PreLoad("fx_overlayEyesBlink.prop")
  PreLoad("fx_overlayEyesBlink.scene")
  PreLoad("fx_overlayEyesIdle.chore")
  PreLoad("fx_riverCampCloudScroll.chore")
  PreLoad("human_eat_1.wav")
  PreLoad("human_eat_2.wav")
  PreLoad("human_eat_3.wav")
  PreLoad("imp_body_fall2.wav")
  PreLoad("imp_fight_heavy_hit_blunt_05.wav")
  PreLoad("imp_fight_heavy_hit_crunch_low_02.wav")
  PreLoad("Imp_JumpInToDirt.wav")
  PreLoad("imp_punch_02.wav")
  PreLoad("imp_punch_05.wav")
  PreLoad("imp_punch_06.wav")
  PreLoad("Inventory.imap")
  PreLoad("logic.scene")
  PreLoad("logic_game.prop")
  PreLoad("logic_game_act1.prop")
  PreLoad("logic_game_act2.prop")
  PreLoad("logic_game_act3.prop")
  PreLoad("logic_game_inventory.prop")
  PreLoad("logic_game_locations.prop")
  PreLoad("logic_game_persistent.prop")
  PreLoad("luke_phoneme_AA.anm")
  PreLoad("luke_phoneme_default.anm")
  PreLoad("luke_phoneme_EE.anm")
  PreLoad("luke_phoneme_FV.anm")
  PreLoad("luke_phoneme_I.anm")
  PreLoad("luke_phoneme_LL.anm")
  PreLoad("luke_phoneme_MM.anm")
  PreLoad("luke_phoneme_NN.anm")
  PreLoad("luke_phoneme_O.anm")
  PreLoad("luke_phoneme_SH.anm")
  PreLoad("luke_phoneme_TH.anm")
  PreLoad("luke_phoneme_U.anm")
  PreLoad("map_environCarCopWindows.d3dtx")
  PreLoad("map_gradiant_zombie200.d3dtx")
  PreLoad("Mesh_1SKN_BMP_CC_TINT_QHi.t3fxb")
  PreLoad("mus_loop_Action_20.wav")
  PreLoad("mus_loop_Hopeful_01.wav")
  PreLoad("mus_sting_Shock_11.wav")
  PreLoad("mus_sting_Shock_13.wav")
  PreLoad("mus_sting_Success_01.wav")
  PreLoad("mus_sting_Success_02.wav")
  PreLoad("Navigate.imap")
  PreLoad("NV_Clem_Breathing_Calm_lp_01.wav")
  PreLoad("NV_Clem_Breathing_Exhausted_lp_01.wav")
  PreLoad("NV_Clem_Breathing_Pain_SewingSkin_lp_01.wav")
  PreLoad("NV_Clem_Breathing_Running_lp_01.wav")
  PreLoad("NV_Clem_Grunt_Exertion-01.wav")
  PreLoad("NV_Clem_Grunt_Exertion-04.wav")
  PreLoad("NV_Clem_Pain_01.wav")
  PreLoad("NV_Clem_Pain_02.wav")
  PreLoad("NV_Clem_Screams_Medium_01.wav")
  PreLoad("obj_arrowCrossbow.d3dmesh")
  PreLoad("obj_arrowCrossbow.prop")
  PreLoad("obj_backpackClementine201.d3dtx")
  PreLoad("obj_barrelRustedRiverCamp.d3dmesh")
  PreLoad("obj_barrelRustedRiverCamp.prop")
  PreLoad("obj_barrelTrashRiverCamp.d3dmesh")
  PreLoad("obj_barrelTrashRiverCamp.prop")
  PreLoad("obj_bbqRustedRiverCamp.d3dmesh")
  PreLoad("obj_bbqRustedRiverCamp.prop")
  PreLoad("obj_beansClumpRiverCamp.d3dmesh")
  PreLoad("obj_beansClumpRiverCamp.prop")
  PreLoad("obj_bowlDogWD.d3dmesh")
  PreLoad("obj_bowlDogWD.d3dtx")
  PreLoad("obj_bowlDogWD.prop")
  PreLoad("obj_boxToysRiverCamp.d3dmesh")
  PreLoad("obj_boxToysRiverCamp.d3dtx")
  PreLoad("obj_boxToysRiverCamp.prop")
  PreLoad("obj_branchHIREZPineClearingCampfire.d3dmesh")
  PreLoad("obj_branchHIREZPineClearingCampfire.prop")
  PreLoad("obj_branchHIRiverCamp.d3dmesh")
  PreLoad("obj_branchHIRiverCamp.prop")
  PreLoad("obj_branchLeavesHIRiverCamp.d3dmesh")
  PreLoad("obj_branchLeavesHIRiverCamp.prop")
  PreLoad("obj_branchTreeRiverCamp.d3dmesh")
  PreLoad("obj_branchTreeRiverCamp.prop")
  PreLoad("obj_campDebrisRiverCamp.d3dtx")
  PreLoad("obj_campDebrisRiverCampB.d3dtx")
  PreLoad("obj_canBeansHotSpot.prop")
  PreLoad("obj_canBeansRiverCamp.prop")
  PreLoad("obj_canBeansRiverCamp.skl")
  PreLoad("obj_canBeansRiverCampA.d3dtx")
  PreLoad("obj_canBeansRiverCampB.d3dtx")
  PreLoad("obj_canBeansRiverCampC.d3dtx")
  PreLoad("obj_canBeansRiverCampLid.d3dmesh")
  PreLoad("obj_canBeansRiverCampLid.prop")
  PreLoad("obj_canBeansRiverCampSaw.d3dmesh")
  PreLoad("obj_canBeansRiverCampSaw.prop")
  PreLoad("obj_canBeansRiverCampSaw.skl")
  PreLoad("obj_canBeansRiverCamp_body.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_clementineWristL_sk38_action_dogWDAttackClem200.anm")
  PreLoad("obj_canBeansRiverCamp_clementineWristL_sk56_clementine200SitsOpenCan_eatFromCan.anm")
  PreLoad("obj_canBeansRiverCamp_clementine_sk56_clementine200DogBiteHoldCan_hitDog.anm")
  PreLoad("obj_canBeansRiverCamp_clementine_sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.anm")
  PreLoad("obj_canBeansRiverCamp_clementine_sk56_idle_clementine200DogBiteHoldCan.anm")
  PreLoad("obj_canBeansRiverCamp_lidA.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidADamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidB.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidBDamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidC.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidCDamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidD.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidDDamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidE.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidEDamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidF.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidFDamaged.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidG.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidOpening.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_lidPeeled.d3dmesh")
  PreLoad("obj_canBeansRiverCamp_sk38_action_dogWDAttackClem200.anm")
  PreLoad("obj_canBeansRiverCamp_sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.anm")
  PreLoad("obj_canBeerRiverCamp.d3dmesh")
  PreLoad("obj_canBeerRiverCamp.prop")
  PreLoad("obj_cardboardRiverCamp.d3dtx")
  PreLoad("obj_coolerBeerRiverCamp.d3dmesh")
  PreLoad("obj_coolerBeerRiverCamp.prop")
  PreLoad("obj_coolerBeerRiverCamp.skl")
  PreLoad("obj_coolerRiverCamp.d3dtx")
  PreLoad("obj_crossbow.d3dmesh")
  PreLoad("obj_crossbow.d3dtx")
  PreLoad("obj_crossbow.prop")
  PreLoad("obj_crossbowArrow.d3dtx")
  PreLoad("obj_crossbowWire.d3dtx")
  PreLoad("obj_dandelion.d3dtx")
  PreLoad("obj_drugstoreOfficeSignsA_text.d3dtx")
  PreLoad("obj_drugstoreOfficeTable.d3dtx")
  PreLoad("obj_dummy.d3dmesh")
  PreLoad("obj_dummy.prop")
  PreLoad("obj_dummy.skl")
  PreLoad("obj_frisbeeRiverCamp.d3dmesh")
  PreLoad("obj_frisbeeRiverCamp.prop")
  PreLoad("obj_grassHighRiverCamp.d3dmesh")
  PreLoad("obj_grassHighRiverCamp.prop")
  PreLoad("obj_grassHIRiverCamp.d3dmesh")
  PreLoad("obj_grassHIRiverCamp.prop")
  PreLoad("obj_grassHIRiverCampWalk.d3dmesh")
  PreLoad("obj_grassHIRiverCampWalk.prop")
  PreLoad("obj_grillRiverCamp.d3dtx")
  PreLoad("obj_groundCoverB.d3dtx")
  PreLoad("obj_hippyBusBlue_interior.d3dtx")
  PreLoad("obj_hippyBusBlue_seats.d3dtx")
  PreLoad("obj_hippyBusBlue_shell.d3dtx")
  PreLoad("obj_hippyBus_hubcap.d3dtx")
  PreLoad("obj_hippyBus_underCarriage.d3dtx")
  PreLoad("obj_knifePocketRiverCamp.d3dmesh")
  PreLoad("obj_knifePocketRiverCamp.d3dtx")
  PreLoad("obj_knifePocketRiverCamp.prop")
  PreLoad("obj_knifePocketRiverCampBloody.d3dtx")
  PreLoad("obj_knifePocketRiverCampBloodyZombie.d3dtx")
  PreLoad("obj_knifePocketRiverCamp_clementineLegR_sk56_clementine200SitsOpenCan_eatFromCan.anm")
  PreLoad("obj_knifePocketRiverCamp_clementine_sk56_clementine200DogBiteStruggleLeft_toDogBiteHoldKnife.anm")
  PreLoad("obj_knifePocketRiverCamp_clementine_sk56_idle_clementine200DogBiteHoldKnife.anm")
  PreLoad("obj_knifePocketRiverCamp_sk38_action_dogWDAttackClem200.anm")
  PreLoad("obj_knifePocketRiverCamp_sk56_clementine200DogBiteStruggleLeft_toDogBiteHoldKnife.anm")
  PreLoad("obj_lightBeamsWD.d3dmesh")
  PreLoad("obj_lightBeamsWD.prop")
  PreLoad("obj_lightBeamWD_alpha.d3dtx")
  PreLoad("obj_logLowRiverCampA.d3dmesh")
  PreLoad("obj_logLowRiverCampA.prop")
  PreLoad("obj_logLowRiverCampB.d3dmesh")
  PreLoad("obj_logLowRiverCampB.prop")
  PreLoad("obj_logRiverCamp.d3dmesh")
  PreLoad("obj_logRiverCamp.prop")
  PreLoad("obj_machetteWD.d3dmesh")
  PreLoad("obj_machetteWD.d3dtx")
  PreLoad("obj_machetteWD.prop")
  PreLoad("obj_photoFamilyRiverCamp.d3dmesh")
  PreLoad("obj_photoFamilyRiverCamp.prop")
  PreLoad("obj_photoPolaroidRiverCamp.d3dmesh")
  PreLoad("obj_photoPolaroidRiverCamp.d3dtx")
  PreLoad("obj_photoPolaroidRiverCamp.prop")
  PreLoad("obj_potRiverCamp.d3dtx")
  PreLoad("obj_riverCampBushA.d3dmesh")
  PreLoad("obj_riverCampBushA.prop")
  PreLoad("obj_riverCampCliff.d3dtx")
  PreLoad("obj_riverCamp_bushClumpA.d3dmesh")
  PreLoad("obj_riverCamp_bushClumpA.prop")
  PreLoad("obj_riverCamp_grassClumpA.d3dmesh")
  PreLoad("obj_riverCamp_grassClumpA.prop")
  PreLoad("obj_riverCamp_grassClumpB.d3dmesh")
  PreLoad("obj_riverCamp_grassClumpB.prop")
  PreLoad("obj_riverwoodsGrass.d3dtx")
  PreLoad("obj_riverwoodsRocksC.d3dtx")
  PreLoad("obj_ropeRiverCamp.d3dmesh")
  PreLoad("obj_ropeRiverCamp.prop")
  PreLoad("obj_ropeRiverCamp.skl")
  PreLoad("obj_ropeRiverCamp_sk54_idle_zombieAverage200DeadTiedTreeMoving.anm")
  PreLoad("obj_RustGarbageCan.d3dtx")
  PreLoad("obj_RustGarbageCanB.d3dtx")
  PreLoad("obj_skyCloudyRiverCamp.d3dmesh")
  PreLoad("obj_skyCloudyRiverCamp.prop")
  PreLoad("obj_sleepingBagRiverCamp.d3dtx")
  PreLoad("obj_tentpoleWD.d3dmesh")
  PreLoad("obj_tentpoleWD.d3dtx")
  PreLoad("obj_tentpoleWD.prop")
  PreLoad("obj_tentpoleWD1_sk38_action_dogWDInjuredThrash.anm")
  PreLoad("obj_tentpoleWD2_sk38_action_dogWDInjuredThrash.anm")
  PreLoad("obj_tentRiverCamp.prop")
  PreLoad("obj_tentRiverCampA.d3dtx")
  PreLoad("obj_tentRiverCampB.d3dtx")
  PreLoad("obj_toyDollScarlett.d3dmesh")
  PreLoad("obj_toyDollScarlett.d3dtx")
  PreLoad("obj_toyDollScarlett.prop")
  PreLoad("obj_toyDollScarlett.skl")
  PreLoad("obj_trashRiverCamp.d3dtx")
  PreLoad("obj_trashRiverCampB.d3dtx")
  PreLoad("obj_treeOakBranchFallBase.d3dtx")
  PreLoad("obj_treeZombieRiverCamp.d3dtx")
  PreLoad("obj_treeZombieRiverCampBMossy.d3dtx")
  PreLoad("obj_treeZombieRiverCampMossy.d3dtx")
  PreLoad("obj_vanRiverCamp.prop")
  PreLoad("obj_zombieMaleAverageHeadB.d3dmesh")
  PreLoad("obj_zombieMaleAverageHeadB.prop")
  PreLoad("obj_zombieTreePocket.prop")
  PreLoad("obj_zombieTreeRiverCamp.d3dmesh")
  PreLoad("obj_zombieTreeRiverCamp.prop")
  PreLoad("Peek.imap")
  PreLoad("punch_low_end_5.wav")
  PreLoad("roll_around_dirt_lp.wav")
  PreLoad("SceneGBuffer_1SKN_QHi.t3fxb")
  PreLoad("SceneGlowAlphaTest_1SKN_QHi.t3fxb")
  PreLoad("SceneGlowAlphaTest_QHi.t3fxb")
  PreLoad("SceneGlow_1SKN_QHi.t3fxb")
  PreLoad("SceneShadowMapAlpha_1SKN_QHi.t3fxb")
  PreLoad("SceneShadowMapAlpha_QHi.t3fxb")
  PreLoad("SceneToonOutline2_1SKN_CC_TINT_QHi.t3fxb")
  PreLoad("SceneToonOutline2_GBuffer_1SKN_QHi.t3fxb")
  PreLoad("SceneVelocityAlpha_1SKN_QHi.t3fxb")
  PreLoad("SceneVelocityAlpha_QHi.t3fxb")
  PreLoad("SceneVelocity_1SKN_QHi.t3fxb")
  PreLoad("sk38_action_dogWDAttackClem200.anm")
  PreLoad("sk38_action_dogWDAttackClem200.chore")
  PreLoad("sk38_action_dogWDInjuredThrash.anm")
  PreLoad("sk38_action_dogWDInjuredThrash.chore")
  PreLoad("sk38_action_dogWDKillsClem.anm")
  PreLoad("sk38_action_dogWDKillsClem.chore")
  PreLoad("sk38_action_dogWDLetsGoOfClem.anm")
  PreLoad("sk38_action_dogWDLetsGoOfClem.chore")
  PreLoad("sk38_dogWD.d3dmesh")
  PreLoad("sk38_dogWD.prop")
  PreLoad("sk38_dogWD.skl")
  PreLoad("sk38_dogWDBiteClem_head.d3dtx")
  PreLoad("sk38_dogWDBiteClem_teeth.d3dtx")
  PreLoad("sk38_dogWDFriendly_sniffGround.anm")
  PreLoad("sk38_dogWDFriendly_toBarking.anm")
  PreLoad("sk38_dogWDNoseStab_head.d3dtx")
  PreLoad("sk38_dogWDSit_tailWag_loop_add.anm")
  PreLoad("sk38_dogWDSit_toFriendly.anm")
  PreLoad("sk38_dogWDSit_weightShift_add.anm")
  PreLoad("sk38_dogWDStandDefense_bark_add.anm")
  PreLoad("sk38_dogWDStandDefense_growl.anm")
  PreLoad("sk38_dogWDStandDefense_growl_add.anm")
  PreLoad("sk38_dogWDStandDefense_whimper.anm")
  PreLoad("sk38_dogWDStandDefense_whimper_add.anm")
  PreLoad("Sk38_dogWDStandFriendly_turn180LeftToWalk.anm")
  PreLoad("Sk38_dogWDStandFriendly_turn180RightToWalk.anm")
  PreLoad("sk38_dogWDwalk_toStandFriendly.anm")
  PreLoad("sk38_dogWD_body.d3dtx")
  PreLoad("sk38_dogWD_body_detail.d3dtx")
  PreLoad("sk38_dogWD_body_nm.d3dtx")
  PreLoad("sk38_dogWD_eye.d3dtx")
  PreLoad("sk38_dogWD_hairAlpha.d3dtx")
  PreLoad("sk38_dogWD_head.d3dtx")
  PreLoad("sk38_dogWD_head_detail.d3dtx")
  PreLoad("sk38_dogWD_head_nm.d3dtx")
  PreLoad("sk38_dogWD_sk56_action_clem200KicksDog.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteHoldCan_hitDog.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteHoldKnife_stabDog.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggleLeft_toDogBiteHoldKnife.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggleLeft_toDogBiteStruggle.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggle_punchDog.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggle_toDogBiteStruggleLeft.anm")
  PreLoad("sk38_dogWD_sk56_clementine200DogBiteStruggle_toDogBiteStruggleRight.anm")
  PreLoad("sk38_dogWD_sk56_idle_clementine200DogBiteHoldCan.anm")
  PreLoad("sk38_dogWD_sk56_idle_clementine200DogBiteHoldKnife.anm")
  PreLoad("sk38_dogWD_sk56_idle_clementine200DogBiteStruggle.anm")
  PreLoad("sk38_dogWD_sk56_idle_clementine200DogBiteStruggleLeft.anm")
  PreLoad("sk38_dogWD_sk56_idle_clementine200DogBiteStruggleRight.anm")
  PreLoad("sk38_dogWD_teeth.d3dtx")
  PreLoad("sk38_dogWD_teeth_nm.d3dtx")
  PreLoad("sk38_dogWD_walk.anm")
  PreLoad("sk38_idle_dogWDBarkingStandDefenseNoBark.anm")
  PreLoad("sk38_idle_dogWDStandDefense.anm")
  PreLoad("sk38_idle_dogWDStandfriendly.anm")
  PreLoad("sk54_idle_zombieAverage200DeadTiedTreeMoving.anm")
  PreLoad("sk54_idle_zombieAverage200DeadTiedTreeMoving.chore")
  PreLoad("sk54_leeOnBackHurt_shoulderPoseTweak.anm")
  PreLoad("sk54_leeOnBackHurt_toLee.anm")
  PreLoad("sk54_leeOnGroundFront_toOnBackHurt.anm")
  PreLoad("sk54_lee_backHurtScramble.anm")
  PreLoad("sk54_lee_poseArmLBackMid_add.anm")
  PreLoad("sk54_lee_poseArmLIn_add.anm")
  PreLoad("sk54_lee_poseArmRFrontMid_add.anm")
  PreLoad("sk54_lee_poseArmRMid_add.anm")
  PreLoad("sk54_lee_poseRightFigersCurlInMediumSpeed_add.anm")
  PreLoad("sk54_lee_poseWristRBendDown_add.anm")
  PreLoad("sk54_lee_poseWristRTwist_add.anm")
  PreLoad("sk54_luke.prop")
  PreLoad("sk54_luke.ptable")
  PreLoad("sk54_luke.skl")
  PreLoad("sk54_luke_body.d3dmesh")
  PreLoad("sk54_luke_body.d3dtx")
  PreLoad("sk54_luke_bodyMacheteHarness.d3dtx")
  PreLoad("sk54_luke_bodyMacheteHarness_detail.d3dtx")
  PreLoad("sk54_luke_bodyMacheteHarness_nm.d3dtx")
  PreLoad("sk54_luke_body_detail.d3dtx")
  PreLoad("sk54_luke_body_nm.d3dtx")
  PreLoad("sk54_luke_hairAlpha.d3dtx")
  PreLoad("sk54_luke_hairCap.d3dtx")
  PreLoad("sk54_luke_hairCap_nm.d3dtx")
  PreLoad("sk54_luke_head.d3dtx")
  PreLoad("sk54_luke_head_detail.d3dtx")
  PreLoad("sk54_luke_head_nm.d3dtx")
  PreLoad("sk54_luke_machete.d3dmesh")
  PreLoad("sk54_luke_macheteSheath.d3dtx")
  PreLoad("sk54_luke_macheteSheath_nm.d3dtx")
  PreLoad("sk54_luke_torso.d3dmesh")
  PreLoad("sk54_luke_torsoMachete.d3dmesh")
  PreLoad("sk54_pete.prop")
  PreLoad("sk54_pete.skl")
  PreLoad("sk54_pete_ankleBite.d3dtx")
  PreLoad("sk54_pete_ankleBite_detail.d3dtx")
  PreLoad("sk54_pete_ankleBite_nm.d3dtx")
  PreLoad("sk54_pete_ankleR.d3dmesh")
  PreLoad("sk54_pete_ankleRBite.d3dmesh")
  PreLoad("sk54_pete_body.d3dmesh")
  PreLoad("sk54_Pete_body.d3dtx")
  PreLoad("sk54_Pete_body_detail.d3dtx")
  PreLoad("sk54_pete_body_nm.d3dtx")
  PreLoad("sk54_Pete_hair.d3dtx")
  PreLoad("sk54_pete_hair_nm.d3dtx")
  PreLoad("sk54_Pete_head.d3dtx")
  PreLoad("sk54_Pete_head_detail.d3dtx")
  PreLoad("sk54_pete_head_nm.d3dtx")
  PreLoad("sk54_wd200GM.ptable")
  PreLoad("sk54_zombie200_armFracture.d3dtx")
  PreLoad("sk54_zombie200_armFracture_Detail.d3dtx")
  PreLoad("sk54_zombie200_armFracture_nm.d3dtx")
  PreLoad("sk54_zombie200_armStump.d3dtx")
  PreLoad("sk54_zombie200_armStump_detail.d3dtx")
  PreLoad("sk54_zombie200_armStump_nm.d3dtx")
  PreLoad("sk54_zombie200_faceB.d3dtx")
  PreLoad("sk54_zombie200_faceB_detail.d3dtx")
  PreLoad("sk54_zombie200_faceB_nm.d3dtx")
  PreLoad("sk54_zombie200_faceC.d3dtx")
  PreLoad("sk54_zombie200_faceC_detail.d3dtx")
  PreLoad("sk54_zombie200_faceC_nm.d3dtx")
  PreLoad("sk54_zombie200_foreArmChop.d3dtx")
  PreLoad("sk54_zombie200_foreArmChop_detail.d3dtx")
  PreLoad("sk54_zombie200_foreArmChop_nm.d3dtx")
  PreLoad("sk54_zombie200_fullArms.d3dtx")
  PreLoad("sk54_zombie200_fullArms_detail.d3dtx")
  PreLoad("sk54_zombie200_fullArms_nm.d3dtx")
  PreLoad("sk54_zombie200_headA.d3dtx")
  PreLoad("sk54_zombie200_headA_detail.d3dtx")
  PreLoad("sk54_zombie200_headA_nm.d3dtx")
  PreLoad("sk54_zombie200_horseShoeHairAAlpha_nm.d3dtx")
  PreLoad("sk54_zombie200_horseShoeHairAblack.d3dtx")
  PreLoad("sk54_zombie200_horseShoeHairAblackAlpha.d3dtx")
  PreLoad("sk54_zombie200_horseShoeHairA_nm.d3dtx")
  PreLoad("sk54_zombie200_jacketABlue.d3dtx")
  PreLoad("sk54_zombie200_jacketABlue_Detail.d3dtx")
  PreLoad("sk54_zombie200_jacketABlue_nm.d3dtx")
  PreLoad("sk54_zombie200_jacketB.d3dtx")
  PreLoad("sk54_zombie200_jacketB_Detail.d3dtx")
  PreLoad("sk54_zombie200_jacketB_nm.d3dtx")
  PreLoad("sk54_zombie200_longHairAAlpha_nm.d3dtx")
  PreLoad("sk54_zombie200_longHairABlack.d3dtx")
  PreLoad("sk54_zombie200_longHairABlackAlpha.d3dtx")
  PreLoad("sk54_zombie200_longHairA_nm.d3dtx")
  PreLoad("sk54_zombie200_missingEye.d3dtx")
  PreLoad("sk54_zombie200_missingEye_nm.d3dtx")
  PreLoad("sk54_zombie200_neckGoreCap.d3dtx")
  PreLoad("sk54_zombie200_neckGoreCap_nm.d3dtx")
  PreLoad("sk54_zombie200_pantsA.d3dtx")
  PreLoad("sk54_zombie200_pantsA_detail.d3dtx")
  PreLoad("sk54_zombie200_pantsA_nm.d3dtx")
  PreLoad("sk54_zombie200_pantsB.d3dtx")
  PreLoad("sk54_zombie200_pantsB_detail.d3dtx")
  PreLoad("sk54_zombie200_pantsB_nm.d3dtx")
  PreLoad("sk54_zombie200_shirtA.d3dtx")
  PreLoad("sk54_zombie200_shirtA_detail.d3dtx")
  PreLoad("sk54_zombie200_shirtA_nm.d3dtx")
  PreLoad("sk54_zombie200_shortsA.d3dtx")
  PreLoad("sk54_zombie200_shortsA_detail.d3dtx")
  PreLoad("sk54_zombie200_shortsA_nm.d3dtx")
  PreLoad("sk54_zombie200_spikeyHairAAlpha_nm.d3dtx")
  PreLoad("sk54_zombie200_spikeyHairAblack.d3dtx")
  PreLoad("sk54_zombie200_spikeyHairAblackAlpha.d3dtx")
  PreLoad("sk54_zombie200_spikeyHairA_nm.d3dtx")
  PreLoad("sk54_zombie200_stragglyHairAblackAlpha.d3dtx")
  PreLoad("sk54_zombie200_summerShirt.d3dtx")
  PreLoad("sk54_zombie200_summerShirt_detail.d3dtx")
  PreLoad("sk54_zombie200_summerShirt_nm.d3dtx")
  PreLoad("sk54_zombie200_teeth.d3dtx")
  PreLoad("sk54_zombie200_teeth_detail.d3dtx")
  PreLoad("sk54_zombie200_teeth_nm.d3dtx")
  PreLoad("sk54_zombieAverage.ptable")
  PreLoad("sk54_zombieAverage200.prop")
  PreLoad("sk54_zombieAverage200.skl")
  PreLoad("sk54_zombieAverage200_armLeftForearmChop.d3dmesh")
  PreLoad("sk54_zombieAverage200_armLeftFull.d3dmesh")
  PreLoad("sk54_zombieAverage200_armLeftFullFracture.d3dmesh")
  PreLoad("sk54_zombieAverage200_armLeftStump.d3dmesh")
  PreLoad("sk54_zombieAverage200_armRightForearmChop.d3dmesh")
  PreLoad("sk54_zombieAverage200_armRightFull.d3dmesh")
  PreLoad("sk54_zombieAverage200_armRightFullFracture.d3dmesh")
  PreLoad("sk54_zombieAverage200_armRightStump.d3dmesh")
  PreLoad("sk54_zombieAverage200_eyeLeftA.d3dmesh")
  PreLoad("sk54_zombieAverage200_eyeLeftMissing.d3dmesh")
  PreLoad("sk54_zombieAverage200_eyeRightA.d3dmesh")
  PreLoad("sk54_zombieAverage200_eyeRightMissing.d3dmesh")
  PreLoad("sk54_zombieAverage200_hairHorseShoe.d3dmesh")
  PreLoad("sk54_zombieAverage200_hairLongA.d3dmesh")
  PreLoad("sk54_zombieAverage200_hairSpikey.d3dmesh")
  PreLoad("sk54_zombieAverage200_hairStraggly.d3dmesh")
  PreLoad("sk54_zombieAverage200_handLeftA.d3dmesh")
  PreLoad("sk54_zombieAverage200_handRightA.d3dmesh")
  PreLoad("sk54_zombieAverage200_headA.d3dmesh")
  PreLoad("sk54_zombieAverage200_headB.d3dmesh")
  PreLoad("sk54_zombieAverage200_headC.d3dmesh")
  PreLoad("sk54_zombieAverage200_headD.d3dmesh")
  PreLoad("sk54_zombieAverage200_legsLongPantsA.d3dmesh")
  PreLoad("sk54_zombieAverage200_legsLongPantsB.d3dmesh")
  PreLoad("sk54_zombieAverage200_legsShortsA.d3dmesh")
  PreLoad("sk54_zombieAverage200_neckGoreCap.d3dmesh")
  PreLoad("sk54_zombieAverage200_teethLowerA.d3dmesh")
  PreLoad("sk54_zombieAverage200_teethUpperA.d3dmesh")
  PreLoad("sk54_zombieAverage200_torsoJacketA.d3dmesh")
  PreLoad("sk54_zombieAverage200_torsoJacketB.d3dmesh")
  PreLoad("sk54_zombieAverage200_torsoSummerShirt.d3dmesh")
  PreLoad("sk54_zombieAverage200_torsoTshirtA.d3dmesh")
  PreLoad("sk54_zombieTree.prop")
  PreLoad("sk54_zombieTree.skl")
  PreLoad("sk54_zombieTree_body.d3dmesh")
  PreLoad("sk54_zombieTree_body.d3dtx")
  PreLoad("sk54_zombieTree_body_detail.d3dtx")
  PreLoad("sk54_zombieTree_body_nm.d3dtx")
  PreLoad("sk54_zombieTree_hair.d3dtx")
  PreLoad("sk54_zombieTree_hairDamageA.d3dtx")
  PreLoad("sk54_zombieTree_hairDamageA_detail.d3dtx")
  PreLoad("sk54_zombieTree_hairDamageB.d3dtx")
  PreLoad("sk54_zombieTree_hairDamageB_detail.d3dtx")
  PreLoad("sk54_zombieTree_hairDamageB_nm.d3dtx")
  PreLoad("sk54_zombieTree_hair_detail.d3dtx")
  PreLoad("sk54_zombieTree_hair_nm.d3dtx")
  PreLoad("sk54_zombieTree_head.d3dtx")
  PreLoad("sk54_zombieTree_head_detail.d3dtx")
  PreLoad("sk54_zombieTree_head_nm.d3dtx")
  PreLoad("sk54_zombieTree_skullCap.d3dmesh")
  PreLoad("sk54_zombieTree_skullCapDamageA.d3dmesh")
  PreLoad("sk54_zombieTree_skullCapDamageB.d3dmesh")
  PreLoad("sk54_zombie_alphaSketch.d3dtx")
  PreLoad("sk54_zombie_eyeball.d3dtx")
  PreLoad("sk54_zombie_eyeball_nm.d3dtx")
  PreLoad("sk54_zombie_headBCaucasianGore.d3dtx")
  PreLoad("sk54_zombie_headBCaucasianGore_nm.d3dtx")
  PreLoad("sk55_zombie200_armFull.d3dtx")
  PreLoad("sk55_zombie200_armFull_detail.d3dtx")
  PreLoad("sk55_zombie200_armFull_nm.d3dtx")
  PreLoad("sk55_zombie200_armStump.d3dtx")
  PreLoad("sk55_zombie200_armStump_detail.d3dtx")
  PreLoad("sk55_zombie200_armStump_nm.d3dtx")
  PreLoad("sk55_zombie200_foreArmChop.d3dtx")
  PreLoad("sk55_zombie200_foreArmChop_detail.d3dtx")
  PreLoad("sk55_zombie200_foreArmChop_nm.d3dtx")
  PreLoad("sk55_zombie200_headA.d3dtx")
  PreLoad("sk55_zombie200_headA_detail.d3dtx")
  PreLoad("sk55_zombie200_headA_nm.d3dtx")
  PreLoad("sk55_zombie200_headB.d3dtx")
  PreLoad("sk55_zombie200_headB_detail.d3dtx")
  PreLoad("sk55_zombie200_headB_nm.d3dtx")
  PreLoad("sk55_zombie200_legsBareA.d3dtx")
  PreLoad("sk55_zombie200_legsBareA_detail.d3dtx")
  PreLoad("sk55_zombie200_legsBareA_nm.d3dtx")
  PreLoad("sk55_zombie200_legsLongPantsA.d3dtx")
  PreLoad("sk55_zombie200_legsLongPantsA_detail.d3dtx")
  PreLoad("sk55_zombie200_legsLongPantsA_nm.d3dtx")
  PreLoad("sk55_zombie200_legsShortShortsA.d3dtx")
  PreLoad("sk55_zombie200_legsShortShortsA_detail.d3dtx")
  PreLoad("sk55_zombie200_legsShortShortsA_nm.d3dtx")
  PreLoad("sk55_zombie200_legsShortSkirt.d3dtx")
  PreLoad("sk55_zombie200_legsShortSkirt_detail.d3dtx")
  PreLoad("sk55_zombie200_legsShortSkirt_nm.d3dtx")
  PreLoad("sk55_zombie200_torsoLongSleeveA.d3dtx")
  PreLoad("sk55_zombie200_torsoLongSleeveA_detail.d3dtx")
  PreLoad("sk55_zombie200_torsoLongSleeveA_nm.d3dtx")
  PreLoad("sk55_zombie200_torsoTshirtA.d3dtx")
  PreLoad("sk55_zombie200_torsoTshirtA_detail.d3dtx")
  PreLoad("sk55_zombie200_torsoTshirtA_nm.d3dtx")
  PreLoad("sk55_zombieAverage200.prop")
  PreLoad("sk55_zombieAverage200.ptable")
  PreLoad("sk55_zombieAverage200.skl")
  PreLoad("sk55_zombieAverage200_armLeftForearmChop.d3dmesh")
  PreLoad("sk55_zombieAverage200_armLeftFull.d3dmesh")
  PreLoad("sk55_zombieAverage200_armLeftStump.d3dmesh")
  PreLoad("sk55_zombieAverage200_armRightForearmChop.d3dmesh")
  PreLoad("sk55_zombieAverage200_armRightFull.d3dmesh")
  PreLoad("sk55_zombieAverage200_armRightStump.d3dmesh")
  PreLoad("sk55_zombieAverage200_eyeLeftA.d3dmesh")
  PreLoad("sk55_zombieAverage200_eyeLeftMissing.d3dmesh")
  PreLoad("sk55_zombieAverage200_eyeRightA.d3dmesh")
  PreLoad("sk55_zombieAverage200_eyeRightMissing.d3dmesh")
  PreLoad("sk55_zombieAverage200_hairStraggly.d3dmesh")
  PreLoad("sk55_zombieAverage200_handLeftA.d3dmesh")
  PreLoad("sk55_zombieAverage200_handRightA.d3dmesh")
  PreLoad("sk55_zombieAverage200_headA.d3dmesh")
  PreLoad("sk55_zombieAverage200_headB.d3dmesh")
  PreLoad("sk55_zombieAverage200_headC.d3dmesh")
  PreLoad("sk55_zombieAverage200_headD.d3dmesh")
  PreLoad("sk55_zombieAverage200_legsBareA.d3dmesh")
  PreLoad("sk55_zombieAverage200_legsLongPantsA.d3dmesh")
  PreLoad("sk55_zombieAverage200_legsShortShortsA.d3dmesh")
  PreLoad("sk55_zombieAverage200_legsShortSkirtA.d3dmesh")
  PreLoad("sk55_zombieAverage200_teethLowerA.d3dmesh")
  PreLoad("sk55_zombieAverage200_teethUpperA.d3dmesh")
  PreLoad("sk55_zombieAverage200_torsoLongSleeveA.d3dmesh")
  PreLoad("sk55_zombieAverage200_torsoTShirt.d3dmesh")
  PreLoad("sk55_zombieFem_hairStraggleyGinger.d3dtx")
  PreLoad("sk55_zombieFem_hairStraggleyGingerAlpha.d3dtx")
  PreLoad("sk55_zombieFem_hairStraggley_nm.d3dtx")
  PreLoad("sk56_action_clem200KicksDog.anm")
  PreLoad("sk56_action_clem200KicksDog.chore")
  PreLoad("sk56_action_clem200StandsUpHurt.anm")
  PreLoad("sk56_clementine200.prop")
  PreLoad("sk56_clementine200.ptable")
  PreLoad("sk56_clementine200.skl")
  PreLoad("sk56_clementine200DogBiteHoldCan_hitDog.anm")
  PreLoad("sk56_clementine200DogBiteHoldCan_hitDog.chore")
  PreLoad("sk56_clementine200DogBiteHoldKnife_stabDog.anm")
  PreLoad("sk56_clementine200DogBiteHoldKnife_stabDog.chore")
  PreLoad("sk56_clementine200DogBiteStruggleLeft_toDogBiteHoldKnife.anm")
  PreLoad("sk56_clementine200DogBiteStruggleLeft_toDogBiteHoldKnife.chore")
  PreLoad("sk56_clementine200DogBiteStruggleLeft_toDogBiteStruggle.anm")
  PreLoad("sk56_clementine200DogBiteStruggleLeft_toDogBiteStruggle.chore")
  PreLoad("sk56_clementine200DogBiteStruggleLeft_toDropCan.anm")
  PreLoad("sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.anm")
  PreLoad("sk56_clementine200DogBiteStruggleRight_toDogBiteHoldCan.chore")
  PreLoad("sk56_clementine200DogBiteStruggle_punchDog.anm")
  PreLoad("sk56_clementine200DogBiteStruggle_punchDog.chore")
  PreLoad("sk56_clementine200DogBiteStruggle_toDogBiteStruggleLeft.anm")
  PreLoad("sk56_clementine200DogBiteStruggle_toDogBiteStruggleLeft.chore")
  PreLoad("sk56_clementine200DogBiteStruggle_toDogBiteStruggleRight.anm")
  PreLoad("sk56_clementine200DogBiteStruggle_toDogBiteStruggleRight.chore")
  PreLoad("sk56_clementine200FearB.ptable")
  PreLoad("sk56_clementine200FearC.ptable")
  PreLoad("sk56_clementine200FearCX.ptable")
  PreLoad("sk56_clementine200HoldHurtArm_pickUpKnife.anm")
  PreLoad("sk56_clementine200HoldHurtArm_toWalkHurtArm.anm")
  PreLoad("sk56_clementine200NormalA.ptable")
  PreLoad("sk56_clementine200PainA.ptable")
  PreLoad("sk56_clementine200PainAX.ptable")
  PreLoad("sk56_clementine200SitsOpenCan_eatFromCan.anm")
  PreLoad("sk56_clementine200SitsOpenCan_eatFromCan.chore")
  PreLoad("sk56_clementine200ThinkingA.ptable")
  PreLoad("sk56_clementine200ThinkingB.ptable")
  PreLoad("sk56_clementine200WalkHurtArm_toHoldHurtArm.anm")
  PreLoad("sk56_clementine200_armLSleeveDown.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveDownBite.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveDownBiteDog.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUp.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUpBandaged.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUpBite.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUpBiteDog.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUpBiteDogDried.d3dmesh")
  PreLoad("sk56_clementine200_armLSleeveUpBiteDogSewn.d3dmesh")
  PreLoad("sk56_clementine200_armRSleeveDown.d3dmesh")
  PreLoad("sk56_clementine200_armRSleeveDownBite.d3dmesh")
  PreLoad("sk56_clementine200_armRSleeveUp.d3dmesh")
  PreLoad("sk56_clementine200_armRSleeveUpBite.d3dmesh")
  PreLoad("sk56_clementine200_backpack.d3dmesh")
  PreLoad("sk56_clementine200_body.d3dmesh")
  PreLoad("sk56_clementine200_body.d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteClean.d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteCleanSewnClosed.d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteCleanSewnClosed_nm .d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteFresh.d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteFresh_detail.d3dtx")
  PreLoad("sk56_clementine200_bodyCloseBiteFresh_nm.d3dtx")
  PreLoad("sk56_clementine200_bodySleeveDownBiteDog.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUp.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUpBandaged.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUpBandaged_detail.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUpBandaged_nm.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUp_detail.d3dtx")
  PreLoad("sk56_clementine200_bodySleevesUp_nm.d3dtx")
  PreLoad("sk56_clementine200_body_detail.d3dtx")
  PreLoad("sk56_clementine200_body_nm.d3dtx")
  PreLoad("sk56_clementine200_eye_nm.d3dtx")
  PreLoad("sk56_clementine200_fingersWiggle.anm")
  PreLoad("sk56_clementine200_hair.d3dtx")
  PreLoad("sk56_clementine200_hairAlpha.d3dtx")
  PreLoad("sk56_clementine200_hairNoHat.d3dtx")
  PreLoad("sk56_clementine200_hairNoHatAlpha.d3dtx")
  PreLoad("sk56_clementine200_hairNoHat_nm.d3dtx")
  PreLoad("sk56_clementine200_hair_detail.d3dtx")
  PreLoad("sk56_clementine200_hair_nm.d3dtx")
  PreLoad("sk56_clementine200_head.d3dtx")
  PreLoad("sk56_clementine200_headHat.d3dmesh")
  PreLoad("sk56_clementine200_headNeckWounds.d3dtx")
  PreLoad("sk56_clementine200_headNeckWounds_nm.d3dtx")
  PreLoad("sk56_clementine200_headNoHat.d3dmesh")
  PreLoad("sk56_clementine200_headNoHat.d3dtx")
  PreLoad("sk56_clementine200_head_detail.d3dtx")
  PreLoad("sk56_clementine200_head_nm.d3dtx")
  PreLoad("sk56_clementine200_leanBack_add.anm")
  PreLoad("sk56_clementine200_leanForwardB_add.anm")
  PreLoad("sk56_clementine200_leanForward_add.anm")
  PreLoad("sk56_clementine200_legL.d3dmesh")
  PreLoad("sk56_clementine200_legLBite.d3dmesh")
  PreLoad("sk56_clementine200_legR.d3dmesh")
  PreLoad("sk56_clementine200_legRBite.d3dmesh")
  PreLoad("sk56_clementine200_moreBreathing.anm")
  PreLoad("sk56_clementine200_neckL.d3dmesh")
  PreLoad("sk56_clementine200_neckLBite.d3dmesh")
  PreLoad("sk56_clementine200_neckR.d3dmesh")
  PreLoad("sk56_clementine200_neckRBite.d3dmesh")
  PreLoad("sk56_clementine200_shrug_add.anm")
  PreLoad("sk56_clementine200_sk38_action_dogWDAttackClem200.anm")
  PreLoad("sk56_clementine200_sk38_action_dogWDKillsClem.anm")
  PreLoad("sk56_clementine200_sk38_action_dogWDLetsGoOfClem.anm")
  PreLoad("sk56_clementine200_slouch_add.anm")
  PreLoad("sk56_clementine200_toAngryCX.chore")
  PreLoad("sk56_clementine200_toFearB.chore")
  PreLoad("sk56_clementine200_toFearC.chore")
  PreLoad("sk56_clementine200_toNormalA.chore")
  PreLoad("sk56_clementine200_walkHurtArm.anm")
  PreLoad("sk56_clementine200_weightShiftAShort_add.anm")
  PreLoad("sk56_clementine200_weightShiftA_add.anm")
  PreLoad("sk56_clementine200_weightShiftB_add.anm")
  PreLoad("sk56_clementine200_weightShiftCShort_add.anm")
  PreLoad("sk56_clementine200_weightShiftC_add.anm")
  PreLoad("sk56_clementine_scaredHandsToFace.anm")
  PreLoad("sk56_idle_clem200AngryCX.anm")
  PreLoad("sk56_idle_clem200FearB.anm")
  PreLoad("sk56_idle_clem200FearC.anm")
  PreLoad("sk56_idle_clem200FearCX.anm")
  PreLoad("sk56_idle_clem200NormalA.anm")
  PreLoad("sk56_idle_clem200PainA.anm")
  PreLoad("sk56_idle_clem200PainAX.anm")
  PreLoad("sk56_idle_clem200SadA.anm")
  PreLoad("sk56_idle_clem200ThinkingA.anm")
  PreLoad("sk56_idle_clem200ThinkingB.anm")
  PreLoad("sk56_idle_clementine200.anm")
  PreLoad("sk56_idle_clementine200.chore")
  PreLoad("sk56_idle_clementine200DogBiteHoldCan.anm")
  PreLoad("sk56_idle_clementine200DogBiteHoldCan.chore")
  PreLoad("sk56_idle_clementine200DogBiteHoldKnife.anm")
  PreLoad("sk56_idle_clementine200DogBiteHoldKnife.chore")
  PreLoad("sk56_idle_clementine200DogBiteStruggle.anm")
  PreLoad("sk56_idle_clementine200DogBiteStruggle.chore")
  PreLoad("sk56_idle_clementine200DogBiteStruggleLeft.anm")
  PreLoad("sk56_idle_clementine200DogBiteStruggleLeft.chore")
  PreLoad("sk56_idle_clementine200DogBiteStruggleRight.anm")
  PreLoad("sk56_idle_clementine200DogBiteStruggleRight.chore")
  PreLoad("sk56_idle_clementine200FearB.chore")
  PreLoad("sk56_idle_clementine200FearC.chore")
  PreLoad("sk56_idle_clementine200FearCX.chore")
  PreLoad("sk56_idle_clementine200PainA.chore")
  PreLoad("sk56_idle_clementine200PainAX.chore")
  PreLoad("sk56_idle_clementine200ThinkingA.chore")
  PreLoad("sk56_idle_clementine200ThinkingB.chore")
  PreLoad("sk56_move_clementine200Walk.chore")
  PreLoad("sk56_move_clementine200WalkAlt.anm")
  PreLoad("sk_wdSharedParts_eyelash_clementine200.d3dtx")
  PreLoad("sk_wdSharedParts_eye_brown200.d3dtx")
  PreLoad("sk_wdSharedParts_eye_clementine200.d3dtx")
  PreLoad("sk_wdSharedParts_eye_nm.d3dtx")
  PreLoad("sk_wdSharedParts_highResZombieMouth.d3dtx")
  PreLoad("sk_wdSharedParts_mouth.d3dtx")
  PreLoad("sk_wdSharedParts_mouth_nm.d3dtx")
  PreLoad("stab_knife_1.wav")
  PreLoad("stick_stab_dirt_5.wav")
  PreLoad("stick_stab_dirt_6.wav")
  PreLoad("tile_barkGeorgiaPine.d3dtx")
  PreLoad("tile_barkGeorgiaPineDark.d3dtx")
  PreLoad("tile_barkLongLeafPine.d3dtx")
  PreLoad("tile_barkOak.d3dtx")
  PreLoad("tile_barkSandPine.d3dtx")
  PreLoad("tile_barkTreeRuralRoad.d3dtx")
  PreLoad("tile_barkWhitePineMossy.d3dtx")
  PreLoad("tile_branchDeadTreePile_alpha.d3dtx")
  PreLoad("tile_cabinExtDeck.d3dtx")
  PreLoad("tile_cabinExtLatticeA.d3dtx")
  PreLoad("tile_cabinExtLatticeB_alp.d3dtx")
  PreLoad("tile_cabinExtRoof.d3dtx")
  PreLoad("tile_cloudsBillowyTop_alpha.d3dtx")
  PreLoad("tile_cloudsBillowy_alpha.d3dtx")
  PreLoad("tile_dirtDetailB_alpha.d3dtx")
  PreLoad("tile_groundPineNeedlesA.d3dtx")
  PreLoad("tile_groundRiverCampPineNeedlesA.d3dtx")
  PreLoad("tile_groupCampGroundDirtGrass.d3dtx")
  PreLoad("tile_leavesMorningGlory_alpha.d3dtx")
  PreLoad("tile_pebblesA.d3dtx")
  PreLoad("tile_pineNeedleSkirt.d3dtx")
  PreLoad("tile_riverCampGroundA.d3dtx")
  PreLoad("tile_riverCampGroundB.d3dtx")
  PreLoad("tile_riverCampGroundC.d3dtx")
  PreLoad("tile_riverCampGroundDetailA.d3dtx")
  PreLoad("tile_rockCrackedA.d3dtx")
  PreLoad("tile_rockInkedA.d3dtx")
  PreLoad("tile_rockInkedAMoss.d3dtx")
  PreLoad("tile_rockInkedCabinExteriorB.d3dtx")
  PreLoad("tile_rockRiverCampWalkA.d3dtx")
  PreLoad("tile_ropeRiverCamp.d3dtx")
  PreLoad("tile_skydomeDrugstoreExterior.d3dtx")
  PreLoad("tile_skydomeDrugstoreExteriorHaze.d3dtx")
  PreLoad("tile_treeBarkWoodsBearTrapB.d3dtx")
  PreLoad("tile_treeDetailMapB.d3dtx")
  PreLoad("tile_woodSidingCabinExt.d3dtx")
  PreLoad("UI.imap")
  PreLoad("ui_coloragent.prop")
  PreLoad("ui_death.chore")
  PreLoad("ui_death.prop")
  PreLoad("ui_death.scene")
  PreLoad("ui_death_background.d3dmesh")
  PreLoad("ui_death_background.d3dtx")
  PreLoad("ui_death_background.prop")
  PreLoad("ui_death_placard.d3dmesh")
  PreLoad("ui_death_placard.d3dtx")
  PreLoad("ui_death_placard.prop")
  PreLoad("ui_death_splat.d3dmesh")
  PreLoad("ui_death_splat.d3dtx")
  PreLoad("ui_death_splat.prop")
  PreLoad("ui_death_text.prop")
  PreLoad("ui_dialog_timer.d3dmesh")
  PreLoad("ui_dialog_timer.d3dtx")
  PreLoad("ui_dialog_timer.prop")
  PreLoad("ui_dialog_timerLine.d3dmesh")
  PreLoad("ui_dialog_timerLine.d3dtx")
  PreLoad("ui_dialog_timerLine.prop")
  PreLoad("ui_episode.dlog")
  PreLoad("ui_faceButton.d3dtx")
  PreLoad("ui_icon_canBeans.d3dtx")
  PreLoad("ui_icon_knifePocket.d3dtx")
  PreLoad("ui_inventory.scene")
  PreLoad("ui_inventory_add.chore")
  PreLoad("ui_inventory_close.chore")
  PreLoad("ui_inventory_icon.prop")
  PreLoad("ui_inventory_inputGamepad.d3dtx")
  PreLoad("ui_inventory_inputHint.chore")
  PreLoad("ui_inventory_inputMouse.d3dtx")
  PreLoad("ui_inventory_open.chore")
  PreLoad("ui_item.prop")
  PreLoad("ui_item_canBeans.prop")
  PreLoad("ui_item_knifePocket.prop")
  PreLoad("ui_loadingBlack_1.d3dtx")
  PreLoad("ui_loadingBlack_2.d3dtx")
  PreLoad("ui_loadingBlack_3.d3dtx")
  PreLoad("ui_loadingBlack_4.d3dtx")
  PreLoad("ui_loadingBlack_5.d3dtx")
  PreLoad("ui_loadingBlack_6.d3dtx")
  PreLoad("ui_loadingBlack_7.d3dtx")
  PreLoad("ui_loadingBlack_8.d3dtx")
  PreLoad("ui_notification.scene")
  PreLoad("ui_notification_saving2.d3dtx")
  PreLoad("ui_notification_saving3.d3dtx")
  PreLoad("ui_notification_saving4.d3dtx")
  PreLoad("ui_notification_saving5.d3dtx")
  PreLoad("ui_notification_saving6.d3dtx")
  PreLoad("ui_notification_saving7.d3dtx")
  PreLoad("ui_notification_saving8.d3dtx")
  PreLoad("ui_overlay.scene")
  PreLoad("ui_padlock_2.wav")
  PreLoad("ui_panicMeter.prop")
  PreLoad("ui_panicMeter.scene")
  PreLoad("ui_panicMeter_background.d3dmesh")
  PreLoad("ui_panicMeter_background.prop")
  PreLoad("ui_panicMeter_fadeOut.chore")
  PreLoad("ui_panicMeter_timerCombat.chore")
  PreLoad("ui_panicMeter_vignette.d3dmesh")
  PreLoad("ui_panicMeter_vignette.d3dtx")
  PreLoad("ui_panicMeter_vignette.prop")
  PreLoad("ui_panicMeter_vignetteRotateLeft.chore")
  PreLoad("ui_panicMeter_vignetteRotateRight.chore")
  PreLoad("ui_peek.prop")
  PreLoad("ui_peek.scene")
  PreLoad("ui_peek_arrow.d3dmesh")
  PreLoad("ui_peek_arrow.d3dtx")
  PreLoad("ui_peek_arrow.prop")
  PreLoad("ui_peek_arrowOff.chore")
  PreLoad("ui_peek_arrowOn.chore")
  PreLoad("ui_reticle.scene")
  PreLoad("ui_reticle_actionExpandPress.chore")
  PreLoad("ui_reticle_actionExpandPress.d3dtx")
  PreLoad("ui_reticle_actionTriggerRight.d3dtx")
  PreLoad("ui_reticle_combatExpand.chore")
  PreLoad("ui_reticle_cursorAcknowledgeIput.chore")
  PreLoad("ui_reticle_textHide.chore")
  PreLoad("ui_reticle_textShow.chore")
  PreLoad("ui_subtitle.scene")
  PreLoad("Univers_Bold.font")
  PreLoad("wd200GM_phoneme_AA.anm")
  PreLoad("wd200GM_phoneme_default.anm")
  PreLoad("wd200GM_phoneme_EE.anm")
  PreLoad("wd200GM_phoneme_FV.anm")
  PreLoad("wd200GM_phoneme_I.anm")
  PreLoad("wd200GM_phoneme_LL.anm")
  PreLoad("wd200GM_phoneme_MM.anm")
  PreLoad("wd200GM_phoneme_NN.anm")
  PreLoad("wd200GM_phoneme_O.anm")
  PreLoad("wd200GM_phoneme_SH.anm")
  PreLoad("wd200GM_phoneme_TH.anm")
  PreLoad("wd200GM_phoneme_U.anm")
  PreLoad("zombieAverage200_phoneme_AA.anm")
  PreLoad("zombieAverage200_phoneme_default.anm")
  PreLoad("zombieAverage200_phoneme_EE.anm")
  PreLoad("zombieAverage200_phoneme_FV.anm")
  PreLoad("zombieAverage200_phoneme_I.anm")
  PreLoad("zombieAverage200_phoneme_LL.anm")
  PreLoad("zombieAverage200_phoneme_MM.anm")
  PreLoad("zombieAverage200_phoneme_NN.anm")
  PreLoad("zombieAverage200_phoneme_O.anm")
  PreLoad("zombieAverage200_phoneme_SH.anm")
  PreLoad("zombieAverage200_phoneme_TH.anm")
  PreLoad("zombieAverage200_phoneme_U.anm")
  PreLoad("zombieAverage_face_default.anm")
  PreLoad("zombieAverage_phoneme_AA.anm")
  PreLoad("zombieAverage_phoneme_default.anm")
  PreLoad("zombieAverage_phoneme_EE.anm")
  PreLoad("zombieAverage_phoneme_FV.anm")
  PreLoad("zombieAverage_phoneme_I.anm")
  PreLoad("zombieAverage_phoneme_LL.anm")
  PreLoad("zombieAverage_phoneme_MM.anm")
  PreLoad("zombieAverage_phoneme_NN.anm")
  PreLoad("zombieAverage_phoneme_O.anm")
  PreLoad("zombieAverage_phoneme_SH.anm")
  PreLoad("zombieAverage_phoneme_TH.anm")
  PreLoad("zombieAverage_phoneme_U.anm")
  PreLoad("bone_crunch_break_thick.wav")
  PreLoad("cam_camCutscene_shakeA_add.anm")
  PreLoad("cam_cutscene_sk54_action_lukeBeheadsZombie.anm")
  PreLoad("clementine200_phoneme_AA_fearA.anm")
  PreLoad("clementine200_phoneme_default_PainB.anm")
  PreLoad("clementine200_phoneme_EE_PainB.anm")
  PreLoad("clementine200_phoneme_FV_PainB.anm")
  PreLoad("clementine200_phoneme_I_PainB.anm")
  PreLoad("clementine200_phoneme_LL_PainB.anm")
  PreLoad("clementine200_phoneme_MM_PainB.anm")
  PreLoad("clementine200_phoneme_NN_PainB.anm")
  PreLoad("clementine200_phoneme_O_PainB.anm")
  PreLoad("clementine200_phoneme_SH_PainB.anm")
  PreLoad("clementine200_phoneme_TH_PainB.anm")
  PreLoad("clementine200_phoneme_U_PainB.anm")
  PreLoad("crossbow_1.wav")
  PreLoad("crossbow_3.wav")
  PreLoad("crossbow_release_1.wav")
  PreLoad("crossbow_release_2.wav")
  PreLoad("env_riverCamp_cs_clemFalls_1.chore")
  PreLoad("env_riverCamp_cs_clemFalls_8.chore")
  PreLoad("fol_arm_leg_slice_gore1.wav")
  PreLoad("fol_bodyfall_dirt_05.wav")
  PreLoad("fol_bodyfall_dirt_09.wav")
  PreLoad("fol_fight_swing_01.wav")
  PreLoad("fol_wet_mud_fall_1.wav")
  PreLoad("fs_hill2.wav")
  PreLoad("fs_hill4.wav")
  PreLoad("fs_hill5.wav")
  PreLoad("fx_bloodSpurtDirWdeB2.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeB_spurt.chore")
  PreLoad("fx_bloodSpurtDirWdeC_spurt.chore")
  PreLoad("fx_bloodSpurtDirWdeD2.d3dtx")
  PreLoad("fx_bloodSpurtDirWdeD_spurt.chore")
  PreLoad("fx_bloodSpurtRadE_spurt.chore")
  PreLoad("fx_bloodSpurtRadG_spurt.chore")
  PreLoad("fx_bloodSpurtRadJ_spurt.chore")
  PreLoad("gore_impact_1.wav")
  PreLoad("gore_impact_2.wav")
  PreLoad("gore_impact_3.wav")
  PreLoad("imp_arm_slice_1.wav")
  PreLoad("imp_Body_Hits_03.wav")
  PreLoad("luke_eyes_down_add.anm")
  PreLoad("luke_eyes_lookAtsOff.chore")
  PreLoad("luke_face_blink.anm")
  PreLoad("luke_face_blink.chore")
  PreLoad("luke_face_blink_add.anm")
  PreLoad("luke_face_browsGestureFurrowQuick_add.anm")
  PreLoad("luke_face_eyesDartsA_add.anm")
  PreLoad("luke_face_eyesDartsB_add.anm")
  PreLoad("luke_face_eyesDartsC_add.anm")
  PreLoad("luke_face_eyesWide_add.anm")
  PreLoad("luke_headGesture_lookDown_add.anm")
  PreLoad("luke_headGesture_lookDown_add.chore")
  PreLoad("luke_headGesture_tiltRightForward_add.anm")
  PreLoad("luke_phoneme_AA_disgustA.anm")
  PreLoad("luke_phoneme_default_disgustA.anm")
  PreLoad("luke_phoneme_EE_disgustA.anm")
  PreLoad("luke_phoneme_FV_disgustA.anm")
  PreLoad("luke_phoneme_I_disgustA.anm")
  PreLoad("luke_phoneme_LL_disgustA.anm")
  PreLoad("luke_phoneme_MM_disgustA.anm")
  PreLoad("luke_phoneme_NN_disgustA.anm")
  PreLoad("luke_phoneme_O_disgustA.anm")
  PreLoad("luke_phoneme_SH_disgustA.anm")
  PreLoad("luke_phoneme_TH_disgustA.anm")
  PreLoad("luke_phoneme_U_disgustA.anm")
  PreLoad("Mesh_BMP_CC_TINT_QHi.t3fxb")
  PreLoad("mus_sting_Shock_09.wav")
  PreLoad("NV_Clem_Screams_Medium_03.wav")
  PreLoad("obj_arrowCrossbow_crossbow_pete_sk54_idle_peteHoldCrossbow.anm")
  PreLoad("obj_arrowCrossbow_crossbow_pete_sk54_peteHoldCrossbow_fire.anm")
  PreLoad("obj_crossbow_pete_sk54_idle_peteHoldCrossbow.anm")
  PreLoad("obj_crossbow_pete_sk54_peteHoldCrossbow_fire.anm")
  PreLoad("obj_machetteWDBloodyZombie.d3dtx")
  PreLoad("obj_zombieMaleAverageHeadB_sk54_action_lukeBeheadsZombie.anm")
  PreLoad("pete_eyes_lookAtsOff.chore")
  PreLoad("pete_face_blink.chore")
  PreLoad("pete_headGesture_lookDownQuickLeft_add.chore")
  PreLoad("pete_headGesture_lookDown_add.chore")
  PreLoad("pete_phoneme_AA_angryA.anm")
  PreLoad("pete_phoneme_default_angryA.anm")
  PreLoad("pete_phoneme_EE_angryA.anm")
  PreLoad("pete_phoneme_FV_angryA.anm")
  PreLoad("pete_phoneme_I_angryA.anm")
  PreLoad("pete_phoneme_LL_angryA.anm")
  PreLoad("pete_phoneme_MM_angryA.anm")
  PreLoad("pete_phoneme_NN_angryA.anm")
  PreLoad("pete_phoneme_O_angryA.anm")
  PreLoad("pete_phoneme_SH_angryA.anm")
  PreLoad("pete_phoneme_TH_angryA.anm")
  PreLoad("pete_phoneme_U_angryA.anm")
  PreLoad("sk54_action_lukeBeheadsZombie.anm")
  PreLoad("sk54_action_lukeBeheadsZombie.chore")
  PreLoad("sk54_idle_lukeDisgustA.anm")
  PreLoad("sk54_idle_lukeDisgustA.chore")
  PreLoad("sk54_idle_lukeNormal.chore")
  PreLoad("sk54_idle_peteAngryA.anm")
  PreLoad("sk54_idle_peteAngryB.anm")
  PreLoad("sk54_idle_peteAngryB.chore")
  PreLoad("sk54_idle_peteAngryD.anm")
  PreLoad("sk54_idle_peteHoldCrossbow.anm")
  PreLoad("sk54_idle_peteHoldCrossbow.chore")
  PreLoad("sk54_lukeDisgustA.ptable")
  PreLoad("sk54_peteAngryA.ptable")
  PreLoad("sk54_peteHoldCrossbow_fire.anm")
  PreLoad("sk54_peteHoldCrossbow_fire.chore")
  PreLoad("sk54_pete_toAngryD.chore")
  PreLoad("sk54_WD200GMDefaultA_leanForwardB_add.anm")
  PreLoad("sk54_wd200GMDefaultA_toFists.anm")
  PreLoad("sk54_wd200GMDefaultA_turnLeft90.anm")
  PreLoad("sk54_WD200GMDefaultB_leanForward_add.anm")
  PreLoad("sk54_WD200GMDefaultC_handsOutLowQuick_add.anm")
  PreLoad("sk54_WD200GMDefaultC_leanForwardB_add.anm")
  PreLoad("sk54_WD200GMDefaultC_leanForward_add.anm")
  PreLoad("sk54_WD200GMDefaultC_shrugWideArms_add.anm")
  PreLoad("sk54_WD200GMFists_weightShiftCShort_add.anm")
  PreLoad("sk54_WD200GMFists_weightShiftC_add.anm")
  PreLoad("sk54_WD200GMFists_weightShiftD_add.anm")
  PreLoad("sk54_wd200GM_lookBehindLeft_add.anm")
  PreLoad("sk54_wd200GM_lookBehindRight_add.anm")
  PreLoad("sk54_zombieAverage200_sk54_action_lukeBeheadsZombie.anm")
  PreLoad("sk54_zombieAverageWalkB_shotBodyB.anm")
  PreLoad("sk54_zombieAverage_headShot.anm")
  PreLoad("sk55_wd200GMRun_toWd200GM.anm")
  PreLoad("sk55_zombieAverageAttackForwardB_headShot.anm")
  PreLoad("sk56_clementine200PainB.ptable")
  PreLoad("sk56_clementine200_headZombieGutsA.d3dtx")
  PreLoad("sk56_clementine200_sk54_action_lukeBeheadsZombie.anm")
  PreLoad("sk56_clementineWalkLeftFootForward_toStop.anm")
  PreLoad("sk56_clementineWalkLeftFootForward_toStop.chore")
  PreLoad("sk56_clementineWalkRightFootForward_toStop.anm")
  PreLoad("sk56_clementineWalkRightFootForward_toStop.chore")
  PreLoad("sk56_idle_clementine200OnGroundButt.anm")
  PreLoad("ui_icon_eye.d3dtx")
  PreLoad("ui_icon_hand.d3dtx")
  PreLoad("vox_zomb_Nat_Attack_long_1.wav")
  PreLoad("vox_zomb_throat_wet_lp_2.wav")
  PreLoad("wd200GM_eyes_downLeft_add.anm")
  PreLoad("wd200GM_eyes_down_add.anm")
  PreLoad("wd200GM_face_blink.anm")
  PreLoad("wd200GM_face_blink_add.anm")
  PreLoad("wd200GM_face_eyesDartsLeftC_add.anm")
  PreLoad("wd200GM_headGesture_lookDown_add.anm")
  PreLoad("wd200GM_headGesture_nodNoQuick_add.anm")
end

function RiverCamp_UpdateZombieWalkBoxes()
  local bFoundZombie = LogicGet("2Camp - Dog Found Zombie")
  local bKilledZombie = LogicGet("2Camp - Killed Zombie")
  for i = 58, 63 do
    WalkBoxesDisableTri(kScene, i, not bFoundZombie)
  end
  for i = 64, 70 do
    WalkBoxesDisableTri(kScene, i, not bFoundZombie or not bKilledZombie)
  end
end

function RiverCamp_OnCanPunctured(spotNum)
  AgentHide("obj_canBeansHotSpot" .. spotNum, true)
  mHolesInCan = mHolesInCan + 1
  if mHolesInCan == 3 then
    Game_RunSceneDialog("cs_canOpen")
  end
end

function RiverCamp_StartDeathTimer()
  if mTimerID then
    return
  end
  mTimerID = Game_RunSceneDialog("bg_deathTimer", false)
  mTimerController = Dialog_GetController(mTimerID)
  if mTimerPercent > 0 then
    ControllerSetTimePercent(mTimerController, mTimerPercent)
  end
end

function RiverCamp_StopDeathTimer(resetPercent)
  if not mTimerID then
    return
  end
  mTimerPercent = ControllerGetTime(mTimerController) / ControllerGetLength(mTimerController)
  DlgStop(mTimerID)
  mTimerID = nil
  resetPercent = resetPercent or 1
  if resetPercent == 0 then
    PanicMeter_FadeOut()
  else
    mTimerPercent = math.max(mTimerPercent - resetPercent, 0)
    PanicMeter_FadeTo(mTimerPercent, 1, 0.21)
  end
end

local OriginalTelltaleLevelStartLogic = function()
  Game_NewScene(kScene, kScript)
  PreloadAssets()
  AgentSetProperty("Clementine", "Render Cull", false)
  RiverCamp_UpdateZombieWalkBoxes()
  if IsPlatformAndroid() then
    AgentSetProperty("cam_closeUp_zombieSmash", "Clip Plane - Near", 0.2)
    AgentSetProperty("cam_cutsceneChore", "Clip Plane - Near", 0.1)
  end
  if Game_GetDebug() and LogicGet("2Camp - Dog Attacked") then
    LogicSet("2Camp - Approached Zombie", true)
    LogicSet("2Camp - Dog Found Zombie", true)
    LogicSet("2Camp - Killed Zombie", true)
    LogicSet("2Camp - Opened Can", true)
    Game_RunSceneDialog("logic_campObjectsOff")
    if not LogicGet("2Camp - Killed Dog") then
      Game_SetSceneDialogNode("cs_dogAttacks")
    else
      Navigate_Enable(false)
      Game_SetSceneDialogNode("cs_exitCamp")
    end
  end
  Game_StartScene(true)
end

--|||||||||||||||||||||||||||||||||||||||||||||||| LEVEL START FUNCTION ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| LEVEL START FUNCTION ||||||||||||||||||||||||||||||||||||||||||||||||
--|||||||||||||||||||||||||||||||||||||||||||||||| LEVEL START FUNCTION ||||||||||||||||||||||||||||||||||||||||||||||||
--Here is the main function that gets called when the level starts.
--This is where we will setup and execute everything that we want to do!

function RiverCamp()
  RELIGHT_ConfigurationStart();

  RELIGHT_ApplyGlobalAdjustments(RelightConfigGlobal);

  --If configured in the development ini, enable the TLSE editor
  if (RelightConfigDevelopment.EditorMode == true) then
    TLSE_Development_Editor_Start();
    Callback_OnPostUpdate:Add(TLSE_Development_Editor_Update);
    do return end --don't continue
  end

  --If configured in the development ini, enable freecamera (if editor is not enabled)
  if (RelightConfigDevelopment.FreeCameraOnlyMode == true) then     
    TLSE_Development_CreateFreeCamera();
    Callback_OnPostUpdate:Add(TLSE_Development_UpdateFreeCamera);
  end

  --If configured in the development ini, enable a performance metrics overlay
  if (RelightConfigDevelopment.PerformanceMetrics == true) then     
    TLSE_Development_PerformanceMetrics_Initalize();
    Callback_OnPostUpdate:Add(TLSE_Development_PerformanceMetrics_Update);
  end

  --If it's configured in the development ini to be in freecamera mode...
  if (RelightConfigDevelopment.FreeCameraOnlyMode == true and RelightConfigDevelopment.FreeCameraOnlyMode_StartSceneNormally == false) then
    return --don't start the scene normally as the user wants to fly around the scene but not have it attempt to run the original level logic
  end

  --execute the original telltale level start logic
  OriginalTelltaleLevelStartLogic();
end

SceneOpen(kScene, kScript)
