local kScript = "HardwareStoreInteriorOffice"
local kScene = "adv_hardwareStoreInteriorOffice"
local PreloadAssets = function()
  if Platform_NeedShaderPreload() then
    print(">>>>>>>>> PRELOADING SHADERS: " .. kScene)
    RenderPreloadShader("Mesh_ENV_LGT_DTL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "263")
    RenderPreloadShader("SceneToonOutline2_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_ENV_LGT_DTL_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_VCOL_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_DTL_SDTL_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_QLo.t3fxb", "264")
    RenderPreloadShader("Mesh_QLo.t3fxb", "266")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "10")
    RenderPreloadShader("SceneToonOutline2_QLo.t3fxb", "128")
    RenderPreloadShader("Mesh_QLo.t3fxb", "138")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_ENV_LGT_QLo.t3fxb", "132")
    RenderPreloadShader("Mesh_ENV_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_ENV_LGT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_1SKN_QLo.t3fxb", "131")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_ENV_LGT_VCOL_QLo.t3fxb", "132")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "142")
    RenderPreloadShader("Mesh_ENV_VCOL_QLo.t3fxb", "142")
    RenderPreloadShader("Mesh_ENV_LGT_VCOL_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_ENV_VCOL_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_VCOL_QLo.t3fxb", "262")
  end
end
function HardwareStoreInteriorOffice()
  Game_NewScene(kScene, kScript)
  Navigate_Enable(false)
  PreloadAssets()
  if IsPlatformAndroid() then
    AgentSetProperty("adv_hardwareStoreInteriorMainOffice_meshesJ", "Render Cull", false)
  end
  Game_StartScene()
end
SceneOpen(kScene, kScript)
