local kScript = "PreviouslyOn"
local kScene = "adv_previouslyOn203"
local Set106Logic = function()
  local russellWent, shelWent, vinceWent, wyattWent
  if S1_ChoiceWasMade(6, "env_truckstopch6_cs_enter_7") or S1_ChoiceWasMade(6, "env_truckstopch6_cs_enter_8") or S1_ChoiceWasMade(6, "env_truckstopch6_cs_enter_9") or S1_ChoiceWasMade(6, "env_truckstopch6_cs_enter_10") then
    Print("Completed 106")
    russellWent = S1_ChoiceWasMade(6, "russell_went - true")
    shelWent = S1_ChoiceWasMade(6, "shel_went - true")
    vinceWent = S1_ChoiceWasMade(6, "vince_went - true")
    wyattWent = S1_ChoiceWasMade(6, "wyatt_went - true")
  else
    Print("106 not completed")
    russellWent = math.random() <= 0.5
    shelWent = not LogicGet("Episode 106 - Killed Stephanie") or math.random() <= 0.5
    vinceWent = LogicGet("Episode 106 - Shot Dan")
    wyattWent = LogicGet("Episode 106 - Left Eddie") or math.random() <= 0.5
  end
  LogicSet("Episode 106 - Russell Went", russellWent)
  LogicSet("Episode 106 - Shel Went", shelWent)
  LogicSet("Episode 106 - Vince Went", vinceWent)
  LogicSet("Episode 106 - Wyatt Went", wyattWent)
end
local PreloadAssets = function()
  PreLoad("env_previouslyOn_CS_Enter_1.chore")
  PreLoad("env_previouslyOn_CS_Enter_3.chore")
  PreLoad("env_previouslyOn_CS_Enter_4.chore")
  PreLoad("env_previouslyOn_CS_Enter_5.chore")
  if not LogicGet("Episode 202 - Nick Dead") then
    PreLoad("env_previouslyOn_CS_Enter_6.chore")
  else
    PreLoad("env_previouslyOn_CS_Enter_7.chore")
  end
  PreLoad("env_previouslyOn_CS_Enter_8.chore")
  PreLoad("env_previouslyOn_CS_Enter_9.chore")
  if not LogicGet("Episode 202 - Alvin Dead") then
    PreLoad("env_previouslyOn_CS_Enter_10.chore")
  else
    PreLoad("env_previouslyOn_CS_Enter_11.chore")
  end
  PreLoad("env_previouslyOn_CS_Enter_13.chore")
  PreLoad("env_previouslyOn_CS_Enter_14.chore")
  if Platform_NeedShaderPreload() then
    print(">>>>>>>>> PRELOADING SHADERS: " .. kScene)
    RenderPreloadShader("SceneShadowMap_QLo.t3fxb", "0")
    RenderPreloadShader("SceneShadowMapAlpha_QLo.t3fxb", "0")
    RenderPreloadShader("SceneShadowMap_1SKN_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "14")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "263")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "268")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "270")
    RenderPreloadShader("FX_Null_QLo.t3fxb", "0")
    RenderPreloadShader("DirectionalLightShadow_QLo.t3fxb", "1024")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_CC_TINT_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_CC_TINT_QLo.t3fxb", "132")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "142")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "142")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "128")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_QLo.t3fxb", "135")
    RenderPreloadShader("SceneSimple_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "64")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "67")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "323")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_CC_TINT_QLo.t3fxb", "196")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_VCOL_CC_TINT_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_BMP_DTL_DBMP_VCOL_CC_TINT_QLo.t3fxb", "204")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("SceneShadowMap_VCOL_QLo.t3fxb", "0")
    RenderPreloadShader("SceneShadowMapAlpha_VCOL_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_LGT_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("SceneToonOutline2_TONE_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_DTL_TONE_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_1SKN_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_LGT_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_1SKN_TONE_QLo.t3fxb", "270")
    RenderPreloadShader("Mesh_1SKN_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_1SKN_TONE_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_1SKN_LGT_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_1SKN_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "131")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "68")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "330")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "266")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "4")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_LGT_CC_TINT_QLo.t3fxb", "324")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "322")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "2")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "2")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "258")
    RenderPreloadShader("SceneShadowMapAlpha_1SKN_QLo.t3fxb", "0")
    RenderPreloadShader("SceneToonOutline2_CC_TINT_QLo.t3fxb", "256")
    RenderPreloadShader("Mesh_DTL_CC_TINT_SDTL_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "74")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "199")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "6")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "262")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "324")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "326")
    RenderPreloadShader("SceneToonOutline2_CC_TONE_QLo.t3fxb", "0")
    RenderPreloadShader("Mesh_DTL_CC_TONE_SDTL_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "3")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "7")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "70")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_1SKN_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "259")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "327")
    RenderPreloadShader("Mesh_LGT_DTL_CC_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_LGT_CC_TONE_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "206")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "135")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_CC_TONE_QLo.t3fxb", "334")
    RenderPreloadShader("Mesh_1SKN_CC_TINT_QLo.t3fxb", "10")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "134")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "324")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "326")
    RenderPreloadShader("Mesh_LGT_VCOL_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_VCOL_CC_TINT_QLo.t3fxb", "198")
    RenderPreloadShader("Mesh_CC_TINT_QLo.t3fxb", "71")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "78")
    RenderPreloadShader("Mesh_LGT_DTL_VCOL_CC_TINT_QLo.t3fxb", "206")
  end
end
function PreviouslyOn()
  Game_NewScene(kScene, kScript)
  Navigate_Enable(false)
  S1_LoadIntoLogic()
  if not Game_GetDebug() then
    PersistentLogic_SetGameLogic()
  end
  Set106Logic()
  PreloadAssets()
  Game_StartScene(true)
end
SceneOpen(kScene, kScript)
